FORMAT: 1A
HOST: https://api.brax.io/v1

# Brax Marketing API 1.0
![Brax Logo](https://brax.io/wp-content/uploads/2017/01/BRAX_Logo_Native-Vector-v2.png)

Welcome to the Brax Marketing API version 1.0.
This API describes how developers can interact with Brax. More information about Brax can be found at [https://brax.io](https://brax.io).

If you have any questions, issues, feature requests, or just want to tell us how much you enjoy using Brax, please let us know at [api@brax.io](mailto:api@brax.io).

## Rate Limits
Each endpoint allows 60 requests per minute from a single IP address. If these limits are exceeded, an HTTP 429 response will be sent in lieu of the usual success response. If the rate limits are exceeded too frequently, we reserve the right to deny further access, thus we encourage responsible usage of our API.

# API Url
The base URL for all API endpoints is [https://api.brax.io/v1](https://api.brax.io/v1).

# Troubleshooting
If you run into trouble, please let us know via [api@brax.io](mailto:api@brax.io). Please attach the `X-Request-Id` header from the returned response. This header allows us to pinpoint your unique request and helps us troubleshoot more effectively.

# Postman
Feel free to take advantage of our Postman collection here: [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/df8ee91a3dd5ad423503#?env%5BBrax%20Marketing%20API%201.0%5D=W3siZW5hYmxlZCI6dHJ1ZSwia2V5IjoiYmFzaWNfdG9rZW4iLCJ2YWx1ZSI6IiIsInR5cGUiOiJ0ZXh0In1d)

## Example [/ping]
In this document, you can click links that look like the one below to get a full description and an example of the request and response for the given endpoint.

### Ping Test [GET]
This is a sanity check when all else fails.

+ Request (application/json)

    + Headers

            Accept:application/json

+ Response 200 (application/json)

    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Body

            {
                "results": "pong"
            }


# Group Overview

The API generally follows the RESTful interface and is structured into the following sections:

- Accounts
- Campaigns
- Ads
- Reports
- Rules
- Users

| Resource  | Actions  |
|:----------|----------|
| Account   | List     |
| Campaign  | List, Read     |
| Ad        | Read     |
| Report    | Read     |
| Rule      | List, Read, Preview, Run, History, Status |
| User      | List     |

## HTTP Requests

Following RESTful conventions, the HTTP method corresponds to the action requested:

| HTTP Method    | Action                      |
|:---------------|-----------------------------|
| `GET`          | List or retrieve a resource |
| `POST`         | Create a resource           |
| `PUT`/`PATCH`  | Update a resource           |
| `DELETE`       | Delete a resource           |

## Pagination

Endpoints that may return large result sets will accept pagination parameters as input and include a **pagination** object in their result sets. These parameters are described as follows.

#### Pagination <a name='Pagination' />



| Field      | Type                           | Example | Description                                                  |
|:-----------|--------------------------------|---------|--------------------------------------------------------------|
| **offset** | <a href='#Integer'>Integer</a> | 0       | starting index of the result set                             |
| **limit**  | <a href='#Integer'>Integer</a> | 100     | maximum possible records in the result set / page size       |
| **count**  | <a href='#Integer'>Integer</a> | 100     | actual number of records in the result set                   |
| **total**  | <a href='#Integer'>Integer</a> | 984     | total number of available records for the requested resource |



## Error Handling
When the API returns a HTTP status code indicating an error (`400`, `401`, `403`, `404`, `429`) it will also include a JSON object describing the error.

```
{
    "timestamp": "2017-06-01 12:00:00",
    "resource": "Accounts Listing",
    "message": "Validation Error",
    "errors": {
        "source": [
            "The selected source is invalid."
        ]
    }
}
```
# Group Authentication

## Authentication [/auth/info]
This API uses [Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) for its authentication.

This means that the HTTP Request should include a header named `Authorization` with a value of `Basic BASE64_ENCODE(YOUR_BRAX_USERNAME:YOUR_BRAX_PASSWORD)`.
Since all communication to the Brax API are HTTPS, your credentials are safe.

Please note that you must use your username and not your email address.

### Authentication Test [GET]

+ Request (application/json)

    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)

    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Body

            {}

+ Response 401 (application/json)

    + Headers
    
            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b
    
    + Body
    
            {
                "timestamp": "2017-05-24 01:07:38",
                "message": "Invalid credentials",
                "errors": null
            }

+ Response 403 (application/json)

    + Headers
    
            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b
    
    + Body
    
            {
                "timestamp": "2017-05-24 01:07:38",
                "message": "API access is not enabled",
                "errors": null
            }
            
# Group Accounts
Endpoints to manage accounts and account settings.

#### Account <a name='Account' />
Represents an account accessible at a network


| Field                 | Type                             | Example                   | Description                                        |
|:----------------------|----------------------------------|---------------------------|----------------------------------------------------|
| **id**                | <a href='#ID'>ID</a> *required*  | 123                       | primary identifier for the account                 |
| **source_account_id** | <a href='#SourceID'>SourceID</a> | 0ad55ae47d03845           | source's unique identifier for the account         |
| **source**            | <a href='#Source'>Source</a>     | outbrain                  | name of the source                                 |
| **name**              | string                           | Selfserve_ACME            | name of the account                                |
| **created_at**        | <a href='#DateTime'>DateTime</a> | 2017-01-21T08:02:43+00:00 | date and time the account was created in Brax      |
| **updated_at**        | <a href='#DateTime'>DateTime</a> | 2017-01-25T08:02:44+00:00 | date and time the account was last updated in Brax |

#### Source <a name='Source' />
String representing an ad network


| Value        | Description                                             |
|:-------------|---------------------------------------------------------|
| `outbrain`   | Outbrain ([www.outbrain.com](//www.outbrain.com))       |
| `taboola`    | Taboola ([www.taboola.com](//www.taboola.com))          |
| `revcontent` | Revcontent ([www.revcontent.com](//www.revcontent.com)) |
| `yahoo`      | Yahoo Gemini ([gemini.yahoo.com](//gemini.yahoo.com))   |
| `content-ad` | Content.ad ([www.content.ad](//content.ad))             |


## Accounts [/accounts{?offset,limit,source}]

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source` (Source, optional) - source name
        + Sample: revcontent

### List Accounts [GET]
List all accounts.

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200
    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes

        - `results` (array[Account])
        - `pagination` (Pagination)

    + Body

            {
                "results": [
                    {
                        "id": "123",
                        "source_account_id": "e010f3346de2e41fed1a288a3ba5cd5e29",
                        "name": "Selfserve_ACME",
                        "source": "outbrain",
                        "created_at": "2016-01-01T01:14:23+00:00",
                        "updated_at": "2017-05-08T21:47:21+00:00"
                    },
                    {
                        "id": "124",
                        "source_account_id": "e010f3346de2e41faa3b288a3ba5cd5e3a",
                        "name": "Selfserve_ACME_2",
                        "source": "outbrain",
                        "created_at": "2016-01-01T17:16:56+00:00",
                        "updated_at": "2017-02-21T20:46:20+00:00"
                    },
                    {
                        "id": "129",
                        "source_account_id": "acmecorporation",
                        "name": "ACME Corporation",
                        "source": "revcontent",
                        "created_at": "2016-01-01T02:50:16+00:00",
                        "updated_at": "2017-05-10T04:02:24+00:00"
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3
                }
            }


# Group Ads
Endpoints to manage ads.

All ads have a **title**, an **image_url**, and a destination **url**.

Ads pushed from Brax with the {{AD_ID}} parameter set in the tracking code will have a **tracking_ad_id** which can be used to enable ad-level tracking for Google Analytics on the `utm_content` parameter.

#### Ad <a name='Ad' />
Represents an ad in a campaign


| Field                  | Type                             | Example                                                                                                 | Description                                                                       |
|:-----------------------|----------------------------------|---------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|
| **source_account_id**  | <a href='#SourceID'>SourceID</a> | ACME-Rockets-SC                                                                                         | source's unique identifier for the account                                        |
| **source_campaign_id** | <a href='#SourceID'>SourceID</a> | 26465874                                                                                                | source's unique campaign identifier                                               |
| **source_ad_id**       | <a href='#SourceID'>SourceID</a> | 0214741                                                                                                 | source's unique ad identifier                                                     |
| **tracking_ad_id**     | string                           | e138da                                                                                                  | identifier provided to the tracking code via `{{AD_ID}}` for ads pushed from Brax |
| **source**             | <a href='#Source'>Source</a>     | taboola                                                                                                 | name of the source                                                                |
| **title**              | string                           | Brax helps you scale with the best                                                                      | ad title / headline                                                               |
| **url**                | <a href='#Url'>Url</a>           | https://brax.io/campaign-tagging-content-distribution/?utm_medium=_&utm_source=Revcontent&utm_content=1 | ad destination url                                                                |
| **image_url**          | <a href='#Url'>Url</a>           | 'https://example.com/test_image_1.jpg'                                                                  | ad image url                                                                      |
| **enabled**            | boolean                          | true                                                                                                    | ad enabled status                                                                 |
| **status**             | string                           | active                                                                                                  | ad status                                                                         |


## Ads [/ads{?offset,limit,source,source_account_id,source_campaign_id}]

### List Ads [GET]
List all ads.

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source` (Source, optional) - source name
        + Sample: revcontent
    + `source_account_id` (SourceID, required) - account id
        + Sample: 123456789
    + `source_campaign_id` (SourceID, optional) -
        + Sample: 987654321

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)
    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes

        - `results` (array[Ad])
        - `pagination` (Pagination)

    + Body
    
            {
                "results": [
                    {
                        "source_account_id": "e010f3346de2e41fed1a288a3ba5cd5e29",
                        "source_campaign_id": "d32c2f3154f2a895ba",
                        "source_ad_id": "342336233",
                        "tracking_ad_id": "ccccbf",
                        "source": "outbrain",
                        "title": "Brax automates the world",
                        "url": "https://brax.io/campaign-tagging-content-distribution/?utm_medium=_&utm_source=outbrain&utm_content=ccccbf",
                        "image_url": "https://example.com/test_image_1.jpg",
                        "enabled": true,
                        "status": "paused"
                    },
                    {
                        "source_account_id": "e010f3346de2e41fed1a288a3ba5cd5e29",
                        "source_campaign_id": "d32c2f3154f2a895ba",
                        "source_ad_id": "342336234",
                        "tracking_ad_id": "8352d9",
                        "source": "outbrain",
                        "title": "Brax automates the world",
                        "url": "https://brax.io/campaign-tagging-content-distribution/?utm_medium=_&utm_source=outbrain&utm_content=8352d9",
                        "image_url": "https://example.com/test_image_2.jpg",
                        "enabled": false,
                        "status": "rejected"
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 2,
                    "total": 2
                }
            }


# Group Campaigns
Endpoints to manage campaigns and campaign settings.

#### Campaign <a name='Campaign' />
Represents a campaign running on a network



| Field                  | Type                                         | Example                   | Description                                         |
|:-----------------------|----------------------------------------------|---------------------------|-----------------------------------------------------|
| **id**                 | <a href='#ID'>ID</a>                         | 234567                    | primary campaign identifier                         |
| **source_account_id**  | <a href='#SourceID'>SourceID</a>             | acmecorporation           | source's unique identifier for the account          |
| **source_campaign_id** | <a href='#SourceID'>SourceID</a>             | 232145547                 | source's unique campaign identifier                 |
| **source**             | <a href='#Source'>Source</a>                 | revcontent                | name of the source                                  |
| **name**               | string                                       | my_first_campaign         | campaign name                                       |
| **start_at**           | <a href='#DateTime'>DateTime</a>             | 2017-01-01T05:00:00+00:00 | campaign start datetime                             |
| **end_at**             | <a href='#DateTime'>DateTime</a>             | 2017-01-31T05:00:00+00:00 | campaign end datetime                               |
| **enabled**            | boolean                                      | true                      | campaign enabled status                             |
| **status**             | <a href='#CampaignStatus'>CampaignStatus</a> | active                    | campaign status                                     |
| **cpc**                | <a href='#Decimal'>Decimal</a>               | 0.08                      | the cost per click assigned to this campaign        |
| **budget_amount**      | <a href='#Decimal'>Decimal</a>               | 105.00                    | the allotted budget for this campaign               |
| **tracking_code**      | string                                       | utm_campaign={{CAMPAIGN}} | tracking code used on ads within this campaign      |
| **created_at**         | <a href='#DateTime'>DateTime</a>             | 2016-12-30T23:18:42+00:00 | date and time the campaign was created in Brax      |
| **updated_at**         | <a href='#DateTime'>DateTime</a>             | 2017-01-25T08:02:43+00:00 | date and time the campaign was last updated in Brax |


#### CampaignStatus <a name='CampaignStatus' />
Running status for a campaign


| Value            | Description                 |
|:-----------------|-----------------------------|
| `active`         | campaign is running         |
| `paused`         | campaign has been paused    |
| `budget_limited` | campaign has met its budget |
| `deleted`        | campaign has been deleted   |


## Campaigns [/campaigns{?offset,limit,source,source_account_id,source_campaign_id}]

### List Campaigns [GET]
List all campaigns.

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source` (Source, optional) - source name
        + Sample: revcontent
    + `source_account_id` (SourceID, required) - account id
        + Sample: 123456789
    + `source_campaign_id` (SourceID, optional) -
        + Sample: 987654321

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json


+ Response 200 (application/json)

    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes

        - `results` (array[Campaign])
        - `pagination` (Pagination)

    + Body

            {
                "results": [
                    {
                        "id": 123,
                        "source_account_id": "Selfserve_ACME",
                        "source_campaign_id": "bf8e5992be46c1e62fd9560b9a2e8c4ad5",
                        "source": "outbrain",
                        "name": "Test Campaign 1",
                        "start_at": "2015-05-27T04:00:00+00:00",
                        "end_at": null,
                        "enabled": false,
                        "status": "paused",
                        "budget_amount": "121.000",
                        "tracking_code": "utm_campaign=Test%20Campaign%201&utm_content={{source_id}}",
                        "created_at": "2016-01-01T00:00:00+00:00",
                        "updated_at": "2017-05-01T01:31:01+00:00",
                        "cpc": "0.051",
                        "cpc_per_ad_enabled": false
                    },
                    {
                        "id": 125,
                        "source_account_id": "Selfserve_ACME",
                        "source_campaign_id": "bf8e5992be46c1e62fd9560b9a2e8c4ad7",
                        "source": "outbrain",
                        "name": "Test Campaign 2",
                        "start_at": "2015-05-27T04:00:00+00:00",
                        "end_at": null,
                        "enabled": false,
                        "status": "paused",
                        "budget_amount": "123.000",
                        "tracking_code": "utm_campaign=Test%20Campaign%202&utm_content={{source_id}}",
                        "created_at": "2016-01-01T00:00:00+00:00",
                        "updated_at": "2017-05-01T01:31:01+00:00",
                        "cpc": "0.061",
                        "cpc_per_ad_enabled": false
                    },
                    {
                        "id": 127,
                        "source_account_id": "Selfserve_ACME",
                        "source_campaign_id": "bf8e5992be46c1e62fd9560b9a2e8c4ad9",
                        "source": "outbrain",
                        "name": "Test Campaign 3",
                        "start_at": "2015-05-27T04:00:00+00:00",
                        "end_at": null,
                        "enabled": false,
                        "status": "paused",
                        "budget_amount": "125.000",
                        "tracking_code": "utm_campaign=Test%20Campaign%203&utm_content={{source_id}}",
                        "created_at": "2016-01-01T00:00:00+00:00",
                        "updated_at": "2017-05-01T01:31:01+00:00",
                        "cpc": "0.071",
                        "cpc_per_ad_enabled": false
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3
                }
            }

# Group Reporting

Performance data can be accessed via endpoints given a date range and filtering parameters.

We will describe the parmeters availalbe for requests and responses, and then list the endpoints below.

# Requests and responses
All reporting endpoints accept a combination of parameters to refine the result set.

#### ReportParams <a name='ReportParams' />
Input parameters for pulling reporting data


| Field                  | Type                                | Example     | Description                                    |
|:-----------------------|-------------------------------------|-------------|------------------------------------------------|
| **offset**             | <a href='#Integer'>Integer</a>      | 0           | starting index of the result set               |
| **limit**              | <a href='#Integer'>Integer</a>      | 100         | maximum number of records to fetch; max: `100` |
| **source**             | <a href='#Source'>Source</a>        | revcontent  | name of the source                             |
| **source_account_id**  | <a href='#SourceID'>SourceID</a>    | acmecompany | source's unique account identifier             |
| **source_campaign_id** | <a href='#SourceID'>SourceID</a>    | 67890       | source's unique campaign identifier            |
| **start_date**         | <a href='#Date'>Date</a> *required* | 2017-02-12  | start date for aggregating metrics             |
| **end_date**           | <a href='#Date'>Date</a> *required* | 2017-02-18  | end date for aggregating metrics               |


#### ReportingMetrics <a name='ReportingMetrics' />
Results will contain these standard performance metrics


| Field           | Type                           | Example    | Description                |
|:----------------|--------------------------------|------------|----------------------------|
| **impressions** | <a href='#Integer'>Integer</a> | 21         | impressions                |
| **clicks**      | <a href='#Integer'>Integer</a> | 4          | clicks                     |
| **conversions** | <a href='#Integer'>Integer</a> | 2          | conversions                |
| **cost**        | <a href='#Decimal'>Decimal</a> | 1.09       | cost                       |
| **ctr**         | <a href='#Decimal'>Decimal</a> | 0.1905     | click through rate         |
| **ecpc**        | <a href='#Decimal'>Decimal</a> | 0.2725     | estimated cost per click   |
| **cpa**         | <a href='#Decimal'>Decimal</a> | 0.545      | cost per action            |
| **icr**         | <a href='#Decimal'>Decimal</a> | 0.09523810 | impression:conversion rate |


#### GoogleAnalyticsMetrics <a name='GoogleAnalyticsMetrics' />
For users with Google Analytics enabled, results will also contain these analytics metrics


| Field                     | Type                                        | Example  | Description              |
|:--------------------------|---------------------------------------------|----------|--------------------------|
| **sessions**              | <a href='#Integer'>Integer</a> *optional*   | 522      | sessions                 |
| **pageviews**             | <a href='#Integer'>Integer</a> *optional*   | 3985     | pageviews                |
| **pageviews_per_session** | <a href='#Decimal'>Decimal</a> *optional*   | 7.6341   | pageviews per session    |
| **bounce_rate**           | <a href='#Decimal'>Decimal</a> *optional*   | 0.0249   | bounce rate              |
| **avg_session_duration**  | <a href='#Duration'>Duration</a> *optional* | 00:05:54 | average session suration |
| **goal_1_completions**    | <a href='#Integer'>Integer</a> *optional*   | 1        | goal #1 completions      |
| **goal_2_completions**    | <a href='#Integer'>Integer</a> *optional*   | 68       | goal #2 completions      |



## Reporting Endpoints [/reports]
Reports can be fetched for a **source** and **source_account_id**; optionally with **source_campaign_id**.

These are the objects that provide performance data:

#### ReportingObject <a name='ReportingObject' />
Entities that export reporting data


| Value       | Description                                                      |
|:------------|------------------------------------------------------------------|
| `campaign`  | Campaigns                                                        |
| `ad`        | Ads                                                              |
| `publisher` | Publishers (Outbrain), Sites (Taboola), and Widgets (Revcontent) |
| `section`   | Sections (Outbrain)                                              |
| `target`    | Targets (Revcontent)                                             |
| `ad_group`  | Ad Groups (Yahoo)                                                |


### Ads Report [GET /reports/ads{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source` (Source, optional) - source name
        + Sample: content-ad
    + `source_account_id` (SourceID, required) - account id
        + Sample: 123456789
    + `source_campaign_id` (SourceID, optional) -
        + Sample: 987654321
    + `start_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-04-17
        
    + `end_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-05-16

+ Request (application/json)
    + Headers
    
            Authorization:Basic {{basic_token}}
            Accept:application/json


+ Response 200 (application/json)

    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes
    
        + `results` (array[AdsReport])
        + `pagination` (Pagination)

    + Body

            {
                "results": [
                    {
                        "source_account_id": "Selfserve_ACME",
                        "source_campaign_id": "85adef34d6a87d00c54fdb561dcc5e0b59",
                        "source_ad_id": "c0e425ea1becbadf1864dd0aa33e87d71b",
                        "tracking_ad_id": "8352d1",
                        "ctr": "0.0075",
                        "ecpc": "0.0200",
                        "cost": "4.4000",
                        "cpa": "0.0000",
                        "icr": "0.000000",
                        "impressions": 29266,
                        "clicks": 220,
                        "conversions": 0
                    },
                    {
                        "source_account_id": "Selfserve_ACME",
                        "source_campaign_id": "85adef34d6a87d00c54fdb561dcc5e0b59",
                        "source_ad_id": "6a3c34102c0694384646005ae4c363ca57",
                        "tracking_ad_id": "8352d7",
                        "ctr": "0.0069",
                        "ecpc": "0.0450",
                        "cost": "12.0700",
                        "cpa": "0.0158",
                        "icr": "0.019779",
                        "impressions": 38677,
                        "clicks": 268,
                        "conversions": 765
                    },
                    {
                        "source_account_id": "Selfserve_ACME_2",
                        "source_campaign_id": "095a5a268d1424ac39d82c49f8365a8f4a",
                        "source_ad_id": "5f09f9526ada9e8ad51682e0f24fdbafe6",
                        "tracking_ad_id": "8352d9",
                        "ctr": "0.0059",
                        "ecpc": "0.0200",
                        "cost": "2.4200",
                        "cpa": "2.4200",
                        "icr": "0.000049",
                        "impressions": 20517,
                        "clicks": 121,
                        "conversions": 1
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3
                }
            }

### Ad Groups Report [GET /reports/ad-groups{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source` (Source, optional) - source name
        + Sample: yahoo
    + `source_account_id` (SourceID, required) - account id
        + Sample: 123456789
    + `source_campaign_id` (SourceID, optional) -
        + Sample: 987654321
    + `start_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-04-17
        
    + `end_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-05-16

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)

    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes
    
        - `results` (array[AdGroupsReport])
        - `pagination` (Pagination)

    + Body

            {
                "results": [
                    {
                        "source_account_id": "123456",
                        "source_campaign_id": "597866360",
                        "source_ad_group_id": "8652979185",
                        "name": "Ad Group A",
                        "ctr": "0.0055",
                        "ecpc": "0.0210",
                        "cost": "2.4230",
                        "cpa": "2.5200",
                        "icr": "0.000149",
                        "impressions": 17,
                        "clicks": 121,
                        "conversions": 1
                    },
                    {
                        "source_account_id": "123456",
                        "source_campaign_id": "597866360",
                        "source_ad_group_id": "7442813551",
                        "name": "Ad Group B",
                        "ctr": "0.0057",
                        "ecpc": "0.0200",
                        "cost": "2.4200",
                        "cpa": "2.4200",
                        "icr": "0.000049",
                        "impressions": 2517,
                        "clicks": 123,
                        "conversions": 131
                    },
                    {
                        "source_account_id": "123457",
                        "source_campaign_id": "654969786",
                        "source_ad_group_id": "3516309393",
                        "name": "Ad Group C",
                        "ctr": "0.0059",
                        "ecpc": "0.0200",
                        "cost": "2.4200",
                        "cpa": "2.4200",
                        "icr": "0.000049",
                        "impressions": 517,
                        "clicks": 125,
                        "conversions": 3
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3
                }
            }


### Campaigns Report [GET /reports/campaigns{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source` (Source, optional) - source name
        + Sample: outbrain
    + `source_account_id` (SourceID, required) - account id
        + Sample: 123456789
    + `source_campaign_id` (SourceID, optional) -
        + Sample: 987654321
    + `start_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-04-17
        
    + `end_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-05-16

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)

    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes
    
        - `results` (array[CampaignsReport])
        - `pagination` (Pagination)

    + Body
    
            {
                "results": [
                    {
                        "source_account_id": "123451",
                        "source_campaign_id": "12345",
                        "name": "Test Campaign 1",
                        "ctr": "0.0055",
                        "ecpc": "0.0210",
                        "cost": "2.4230",
                        "cpa": "2.5200",
                        "icr": "0.000149",
                        "impressions": 17,
                        "clicks": 121,
                        "conversions": 1,
                        "sessions": null,
                        "pageviews": null,
                        "pageviews_per_session": null,
                        "bounce_rate": null,
                        "avg_session_duration": null,
                        "goal_1_completions": null,
                        "goal_2_completions": null
                    },
                    {
                        "source_account_id": "123455",
                        "source_campaign_id": "12346",
                        "name": "Test Campaign 2",
                        "ctr": "0.0057",
                        "ecpc": "0.0200",
                        "cost": "2.4200",
                        "cpa": "2.4200",
                        "icr": "0.000049",
                        "impressions": 2517,
                        "clicks": 123,
                        "conversions": 131,
                        "sessions": null,
                        "pageviews": null,
                        "pageviews_per_session": null,
                        "bounce_rate": null,
                        "avg_session_duration": null,
                        "goal_1_completions": null,
                        "goal_2_completions": null
                    },
                    {
                        "source_account_id": "123459",
                        "source_campaign_id": "12347",
                        "name": "Test Campaign 3",
                        "ctr": "0.0059",
                        "ecpc": "0.0200",
                        "cost": "2.4200",
                        "cpa": "2.4200",
                        "icr": "0.000049",
                        "impressions": 517,
                        "clicks": 125,
                        "conversions": 3,
                        "sessions": null,
                        "pageviews": null,
                        "pageviews_per_session": null,
                        "bounce_rate": null,
                        "avg_session_duration": null,
                        "goal_1_completions": null,
                        "goal_2_completions": null
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3
                }
            }


### Publishers Report [GET /reports/publishers{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source` (Source, optional) - source name
        + Sample: revcontent
    + `source_account_id` (SourceID, required) - account id
        + Sample: 123456789
    + `source_campaign_id` (SourceID, optional) -
        + Sample: 987654321
    + `start_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-04-17
        
    + `end_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-05-16

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json


+ Response 200 (application/json)
    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b
    
    + Attributes

        - `results` (array[PublishersReport])
        - `pagination` (Pagination)

    + Body

            {
                "results": [
                    {
                        "source_account_id": "123456",
                        "source_campaign_id": "597866360",
                        "source_publisher_id": "00a4cb19d55ea630d69fba33dba5d44106",
                        "name": "previously.tv",
                        "ctr": "0.0136",
                        "ecpc": "0.8267",
                        "cost": "548.9100",
                        "cpa": "274.4550",
                        "icr": "0.0000",
                        "impressions": 48902,
                        "clicks": 664,
                        "conversions": 2,
                        "conversion_rate": "0.0030",
                        "sessions": "522",
                        "pageviews": "3985",
                        "pageviews_per_session": "7.6341",
                        "bounce_rate": "0.0249",
                        "avg_session_duration": "00:05:54",
                        "goal_1_completions": "1",
                        "goal_2_completions": "68"
                    },
                    {
                        "source_account_id": "123456",
                        "source_campaign_id": "597866360",
                        "source_publisher_id": "00f5489fcb230267aba360a47a9f93b3d6",
                        "name": "Rebel Circus (Sell It Social)",
                        "ctr": "0.0161",
                        "ecpc": "1.2802",
                        "cost": "649.0700",
                        "cpa": "649.0700",
                        "icr": "0.0000",
                        "impressions": 31475,
                        "clicks": 507,
                        "conversions": 1,
                        "conversion_rate": "0.0020",
                        "sessions": "275",
                        "pageviews": "1390",
                        "pageviews_per_session": "5.0545",
                        "bounce_rate": "0.0618",
                        "avg_session_duration": "00:02:40",
                        "goal_1_completions": "1",
                        "goal_2_completions": "44"
                    },
                    {
                        "source_account_id": "123457",
                        "source_campaign_id": "654969786",
                        "source_publisher_id": "00795491b416e2a259b0be2fd2835bbdb0",
                        "name": "thepoplr (Pitria)",
                        "ctr": "0.0053",
                        "ecpc": "0.9360",
                        "cost": "338.8300",
                        "cpa": "112.9433",
                        "icr": "0.0000",
                        "impressions": 68723,
                        "clicks": 362,
                        "conversions": 3,
                        "conversion_rate": "0.0083",
                        "sessions": "269",
                        "pageviews": "1313",
                        "pageviews_per_session": "4.8810",
                        "bounce_rate": "0.0483",
                        "avg_session_duration": "00:05:37",
                        "goal_1_completions": "3",
                        "goal_2_completions": "59"
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3 
                }
            }


### Sections Report [GET /reports/sections{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source` (Source, optional) - source name
        + Sample: outbrain
    + `source_account_id` (SourceID, required) - account id
        + Sample: 123456789
    + `source_campaign_id` (SourceID, optional) -
        + Sample: 987654321
    + `start_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-04-17
        
    + `end_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-05-16

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json



+ Response 200 (application/json)
    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b
    
    + Attributes

        - `results` (array[SectionsReport])
        - `pagination` (Pagination)

    + Body

            {
                "results": [
                    {
                        "source_account_id": "123456",
                        "source_campaign_id": "597866360",
                        "source_publisher_id": "00a4cb19d55ea630d69fba33dba5d44106",
                        "source_section_id": "00a4cb91d55ea63d069fab3d3b5ad41460",
                        "publisher_name": "Test Publisher 1",
                        "name": "previously.tv",
                        "ctr": "0.0136",
                        "ecpc": "0.8267",
                        "cost": "548.9100",
                        "cpa": "274.4550",
                        "icr": "0.0000",
                        "impressions": 48902,
                        "clicks": 664,
                        "conversions": 2,
                        "conversion_rate": "0.0030",
                        "sessions": "522",
                        "pageviews": "3985",
                        "pageviews_per_session": "7.6341",
                        "bounce_rate": "0.0249",
                        "avg_session_duration": "00:05:54",
                        "goal_1_completions": "1",
                        "goal_2_completions": "68"
                    },
                    {
                        "source_account_id": "123456",
                        "source_campaign_id": "597866360",
                        "source_publisher_id": "00f5489fcb230267aba360a47a9f93b3d6",
                        "source_section_id": "00a4cb91d55ea63d069fab3d3b5ad41460",
                        "publisher_name": "Test Publisher 2",
                        "name": "Rebel Circus (Sell It Social)",
                        "ctr": "0.0161",
                        "ecpc": "1.2802",
                        "cost": "649.0700",
                        "cpa": "649.0700",
                        "icr": "0.0000",
                        "impressions": 31475,
                        "clicks": 507,
                        "conversions": 1,
                        "conversion_rate": "0.0020",
                        "sessions": "275",
                        "pageviews": "1390",
                        "pageviews_per_session": "5.0545",
                        "bounce_rate": "0.0618",
                        "avg_session_duration": "00:02:40",
                        "goal_1_completions": "1",
                        "goal_2_completions": "44"
                    },
                    {
                        "source_account_id": "123457",
                        "source_campaign_id": "654969786",
                        "source_publisher_id": "00795491b416e2a259b0be2fd2835bbdb0",
                        "source_section_id": "00a4cb91d55ea63d069fab3d3b5ad41460",
                        "publisher_name": "Test Publisher 3",
                        "name": "thepoplr (Pitria)",
                        "ctr": "0.0053",
                        "ecpc": "0.9360",
                        "cost": "338.8300",
                        "cpa": "112.9433",
                        "icr": "0.0000",
                        "impressions": 68723,
                        "clicks": 362,
                        "conversions": 3,
                        "conversion_rate": "0.0083",
                        "sessions": "269",
                        "pageviews": "1313",
                        "pageviews_per_session": "4.8810",
                        "bounce_rate": "0.0483",
                        "avg_session_duration": "00:05:37",
                        "goal_1_completions": "3",
                        "goal_2_completions": "59"
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3 
                }
            }


## Targets Report [GET /reports/targets{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100
    + `source`: (Source, optional) - source name
        + Sample: revcontent
    + `source_account_id` (SourceID, required) - account id
        + Sample: 123456789
    + `source_campaign_id` (SourceID, optional) -
        + Sample: 987654321
    + `start_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-04-17
        
    + `end_date` (Date, optional) -
        + Default: yesterday
        + Sample: 2017-05-16

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json


+ Response 200 (application/json)
    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b
    
    + Attributes

        - `results` (array[TargetsReport])
        - `pagination` (Pagination)

    + Body

            {
                "results": [
                    {
                        "source_account_id": "123456",
                        "source_campaign_id": "597866360",
                        "source_target_id": "74",
                        "name": "Celebrity & Gossip",
                        "bid": "0.030",
                        "bid_type": "cpc",
                        "ctr": "0.0136",
                        "ecpc": "0.8267",
                        "cost": "548.9100",
                        "cpa": "274.4550",
                        "icr": "0.0000",
                        "impressions": 48902,
                        "clicks": 664,
                        "conversions": 2,
                        "conversion_rate": "0.0030",
                        "sessions": "522",
                        "pageviews": "3985",
                        "pageviews_per_session": "7.6341",
                        "bounce_rate": "0.0249",
                        "avg_session_duration": "00:05:54",
                        "goal_1_completions": "1",
                        "goal_2_completions": "68"
                    },
                    {
                        "source_account_id": "123456",
                        "source_campaign_id": "597866360",
                        "source_target_id": "75",
                        "name": "Conservative News",
                        "bid": "0.030",
                        "bid_type": "cpc",
                        "ctr": "0.0161",
                        "ecpc": "1.2802",
                        "cost": "649.0700",
                        "cpa": "649.0700",
                        "icr": "0.0000",
                        "impressions": 31475,
                        "clicks": 507,
                        "conversions": 1,
                        "conversion_rate": "0.0020",
                        "sessions": "275",
                        "pageviews": "1390",
                        "pageviews_per_session": "5.0545",
                        "bounce_rate": "0.0618",
                        "avg_session_duration": "00:02:40",
                        "goal_1_completions": "1",
                        "goal_2_completions": "44"
                    },
                    {
                        "source_account_id": "123457",
                        "source_campaign_id": "654969786",
                        "source_target_id": "76",
                        "name": "Faith, Uplifting & Inspirational",
                        "bid": "0.030",
                        "bid_type": "cpc",
                        "ctr": "0.0053",
                        "ecpc": "0.9360",
                        "cost": "338.8300",
                        "cpa": "112.9433",
                        "icr": "0.0000",
                        "impressions": 68723,
                        "clicks": 362,
                        "conversions": 3,
                        "conversion_rate": "0.0083",
                        "sessions": "269",
                        "pageviews": "1313",
                        "pageviews_per_session": "4.8810",
                        "bounce_rate": "0.0483",
                        "avg_session_duration": "00:05:37",
                        "goal_1_completions": "3",
                        "goal_2_completions": "59"
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3
                }
            }

# Group Rules
Endpoints to manage rules, rule settings, preview running rules, run rules, and rule job statuses.

Rules allow bulk modification of campaign settings based on a filter and a condition.

<a href='#Filter'>Filter</a>s enable matching only within certain networks, accounts, or individual campaigns. These parameters are also used when querying the reporting system and are applied using logical `OR`. This means you can request matching on several accounts for the same rule, or attempt matching for all accounts by default to keep the criteria as broad as possible.

<a href='#Condition'>Condition</a>s specify how objects are selected for applying changes, and include a metric, operator, expected value, and a date range. These parameters are used when querying the reporting system and are applied using logical `AND`. This means the more conditions applied, the more narrow the matching criteria.

A rule will always have at least one filter one condition, and its first condition will always use the `campaign.cost` metric.

The following rule types are supported...

#### RuleType <a name='RuleType' />
Describes the type of rule, indicates what it affects and how

Starred rule types will have an **amount** specified in the rule.

| Value                   | Description                 |
|:------------------------|-----------------------------|
| `pause_campaign`        | Pause Campaigns             |
| `pause_ad`              | Pause Ads                   |
| `block_publisher`       | Block Publishers            |
| `block_section`         | Block Sections (Outbrain)   |
| `block_target`          | Block Targets (Revcontent)  |
| `pause_ad_group`        | Pause Ad Groups (Yahoo)     |
| `modify_bid_publisher`  | Update Site Bid Modifiers * |
| `multiply_bid_target`   | Update Target Bids *        |
| `multiply_bid_campaign` | Update Campaign Bids *      |


## Get Rules [/rules]

The structure of a rule and its constituents are described as follows...

#### Rule <a name='Rule' />




| Field          | Type                                                   | Example                    | Description                                                                                                       |
|:---------------|--------------------------------------------------------|----------------------------|-------------------------------------------------------------------------------------------------------------------|
| **id**         | <a href='#ID'>ID</a>                                   | 986                        | rule primary identifier                                                                                           |
| **name**       | string *required*                                      | Pause poor performaing ads | name of the rule                                                                                                  |
| **type**       | <a href='#RuleType'>RuleType</a> *required*            | pause_ad                   | determines what actions are performed on which objects                                                            |
| **amount**     | <a href='#Decimal'>Decimal</a> *optional*              | 1.2500                     | value or multiplier by which to modify existing bids or values; `null` if amount does not apply to this rule type |
| **conditions** | array of <a href='#Condition'>Condition</a> *required* |                            | criteria for matching                                                                                             |
| **filters**    | array of <a href='#Filter'>Filter</a> *required*       |                            | restrict search to source, account, or campaign level                                                             |
| **created_at** | <a href='#DateTime'>DateTime</a>                       | 2017-01-21T08:02:43+00:00  | date and time the rule was created in Brax                                                                        |
| **updated_at** | <a href='#DateTime'>DateTime</a>                       | 2017-01-25T08:02:43+00:00  | date and time the rule was last updated in Brax                                                                   |


#### Filter <a name='Filter' />



| Field           | Type                         | Example | Description                           |
|:----------------|------------------------------|---------|---------------------------------------|
| **id**          | <a href='#ID'>ID</a>         | 87      | filter primary identifier             |
| **source**      | <a href='#Source'>Source</a> | taboola | restrict search to the given network  |
| **account_id**  | <a href='#ID'>ID</a>         | 96751   | restrict search to the given account  |
| **campaign_id** | <a href='#ID'>ID</a>         | 452677  | restrict search to the given campaign |

- Filters may specify a **source**, an **account_id**, and a **campaign_id**, or can be set to `null` indicating non-specific.
- For example, a filter can have **source** set to `outbrain`, **account_id** set to `3216`, and **campaign_id** set to `null` to ask for any campaign in the Outbrain account whose ID is `3216`.
- A filter can also have all optional values set to `null` to indicate "include all networks, accounts, and campaigns known to Brax".
- Or a filter may specify only **source** and leave the other two `null` to indicate only campaigns in the given network.
- If **campaign_id** is set, the other two must also be set, and likewise when **account_id** is set, **source** must also be set.

#### Condition <a name='Condition' />
Criteria required to match target objects, e.g. `campaign.cost` `<` `10` `last_7_days`




| Field          | Type                                          | Example       | Description                                                       |
|:---------------|-----------------------------------------------|---------------|-------------------------------------------------------------------|
| **id**         | <a href='#ID'>ID</a>                          | 721           | condition primary identifier                                      |
| **metric**     | <a href='#Metric'>Metric</a> *required*       | campaign.cost | metric for input criteria                                         |
| **operator**   | <a href='#Operator'>Operator</a> *required*   | <             | comparison operator to apply                                      |
| **value**      | <a href='#Decimal'>Decimal</a> *required*     | 10            | expected value for comparison                                     |
| **date_range** | <a href='#DateRange'>DateRange</a> *required* | last_7_days   | reporting range to aggregate metrics                              |
| **start_date** | <a href='#Date'>Date</a>                      | 2017-02-12    | start date for aggregating metrics (determined by **date_range**) |
| **end_date**   | <a href='#Date'>Date</a>                      | 2017-02-12    | end date for aggregating metrics (determined by **date_range**)   |


#### Metric <a name="Metric" />
Metric is a string composed of an object and a metric separated by a dot, i.e. **reporting_object**.**metric_field**

Reporting object can be one of: `campaign`, `ad`, `publisher`, `target`, `section`, `ad_group`

Metric field can be one of the standard <a href="#ReportingMetrics">ReportingMetrics</a>:

`impressions`, `clicks`, `conversions`, `cost`, `ctr`, `ecpc`, `cpa`, `icr`

Or one of the <a href="#GoogleAnalyticsMetrics">GoogleAnalyticsMetrics</a>:

`sessions`, `pageviews`, `pageviews_per_session`, `bounce_rate`, `avg_session_duration`, `goal_1_completions`, `goal_2_completions`

**Examples**

- `campaign.clicks` - Clicks for a campaign
- `target.ctr` - Click-through rate for a target
- `publisher.conversions` - Number of conversions for a publisher

### List Rules [GET /rules{?offset,limit}]

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json



+ Response 200 (application/json)

    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes
        + `results` (array[Rule])
        + `pagination` (Pagination)

    + Body

            {
              "results": [
                {
                  "id": 132,
                  "name": "my pause campaign rule",
                  "type": "pause_campaign",
                  "amount": null,
                  "conditions": [
                    {
                      "id": 75,
                      "metric": "campaign.cost",
                      "operator": ">",
                      "value": "10",
                      "date_range": "last_7_days"
                    }
                  ],
                  "filters": [
                    {
                      "id": 67,
                      "source": null,
                      "account_id": null,
                      "campaign_id": null
                    }
                  ],
                  "created_at": "2017-04-21T20:26:32+00:00",
                  "updated_at": "2017-04-21T20:26:32+00:00"
                },
                {
                  "id": 144,
                  "name": "my ads rule",
                  "type": "pause_ad",
                  "amount": null,
                  "conditions": [
                    {
                      "id": 81,
                      "metric": "campaign.cost",
                      "operator": ">",
                      "value": "10.00",
                      "date_range": "last_7_days"
                    },
                    {
                      "id": 86,
                      "metric": "ad.cpa",
                      "operator": "<",
                      "value": "8",
                      "date_range": "last_2_days_inclusive"
                    }
                  ],
                  "filters": [
                    {
                      "id": 74,
                      "source": "outbrain",
                      "account_id": 2,
                      "campaign_id": null
                    }
                  ],
                  "created_at": "2017-04-25T18:08:48+00:00",
                  "updated_at": "2017-04-25T18:08:48+00:00"
                },
                {
                  "id": 150,
                  "name": "block my publishers",
                  "type": "block_publisher",
                  "amount": null,
                  "conditions": [
                    {
                      "id": 89,
                      "metric": "campaign.cost",
                      "operator": ">",
                      "value": "10.00",
                      "date_range": "last_7_days"
                    },
                    {
                      "id": 90,
                      "metric": "publisher.cost",
                      "operator": ">",
                      "value": "0",
                      "date_range": "last_7_days"
                    }
                  ],
                  "filters": [
                    {
                      "id": 80,
                      "source": null,
                      "account_id": null,
                      "campaign_id": null
                    }
                  ],
                  "created_at": "2017-04-26T16:44:43+00:00",
                  "updated_at": "2017-04-26T16:44:43+00:00"
                }
              ],
              "pagination": {
                "offset": 0,
                "limit": 100,
                "count": 3,
                "total": 3
              }
            }


### Rule by ID [GET /rules/{rule_id}]

+ Parameters
    + `rule_id` (ID, required)

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)
    + Attributes (Rule)

    + Body

            {
                "id": 132,
                "name": "my pause campaign rule",
                "type": "pause_campaign",
                "amount": null,
                "conditions": [
                    {
                        "id": 75,
                        "metric": "campaign.cost",
                        "operator": ">",
                        "value": "10",
                        "date_range": "last_7_days"
                    }
                ],
                "filters": [
                    {
                        "id": 67,
                        "source": null,
                        "account_id": null,
                        "campaign_id": null
                    }
                ],
                "created_at": "2017-04-21T20:26:32+00:00",
                "updated_at": "2017-04-21T20:26:32+00:00"
            }


## Running Rules [/rules/{rule_id}]

Before running a rule, you may want to find out what the rule will do.
The preview endpoint can be used to return details showing potential result of running a rule, including the current rule settings, and the affected objects.

A POST request sent to the run endpoint will enqueue the running of the specified rule with the default match items selected,
and return a response with the `job_id` of the job which can be queried via the status endpoint below.


Rule previews have the following structure...
#### RulePreview <a name='RulePreview' />


| Field       | Type                                | Description                                              |
|:------------|-------------------------------------|----------------------------------------------------------|
| **rule**    | <a href='#Rule'>Rule</a>            | the rule being previewed                                 |
| **matches** | array of <a href='#Match'>Match</a> | list of matched items to be affected by running the rule |

#### Match <a name='Match' />


| Field                    | Type                         | Example           | Description                                                                                      |
|:-------------------------|------------------------------|-------------------|--------------------------------------------------------------------------------------------------|
| **source**               | <a href='#Source'>Source</a> | yahoo             | source of the affected object                                                                    |
| **account_id**           | <a href='#ID'>ID</a>         | 65437             | identifier of the account of the affected object                                                 |
| **campaign_id**          | <a href='#ID'>ID</a>         | 34634             | identifier of the campaign to be affected                                                        |
| **account_name**         | string                       | Selfserve_ACME    | name of the account of the affected object                                                       |
| **campaign_name**        | string                       | my_first_campaign | name of the affected campaign                                                                    |
| *object metric1 range* | string                       | $124.56           | metric values of the affected objects for the given date range, e.g. `campaign cost last_7_days` |
| *object metric2 range* | string                       | 0.2843            | metric values of the affected objects for the given date range, e.g. `campaign ctr last_7_days`  |


Depending on how a rule is configured, there will be multiple object metrics shown in the response. The field names will contain spaces for these metrics.

### Preview a Rule by ID [GET /rules/{rule_id}/preview]

+ Parameters
    + `rule_id` (ID, required)

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)
    + Attributes (RulePreview)

    + Body

            {
              "rule": {
                "id": 132,
                "name": "Pause poor performing campaigns",
                "type": "pause_campaign",
                "amount": null,
                "conditions": [
                  {
                    "id": 75,
                    "metric": "campaign.cost",
                    "operator": ">",
                    "value": "10",
                    "date_range": "last_7_days",
                    "start_date": "2017-05-19",
                    "end_date": "2017-05-25"
                  },
                  {
                  "id": 76,
                  "metric": "campaign.ctr",
                  "operator": "<",
                  "value": "0.05",
                  "date_range": "last_7_days"
                }
                ],
                "filters": [
                  {
                    "id": 67,
                    "source": null,
                    "account_id": null,
                    "campaign_id": null
                  }
                ],
                "created_at": "2017-04-21T20:26:32+00:00",
                "updated_at": "2017-04-21T20:26:32+00:00"
              },
              "matches": [
                {
                  "source": "yahoo",
                  "account_id": 90001,
                  "campaign_id": 52222,
                  "account_name": "brax-test-account",
                  "campaign_name": "brax-test-us",
                  "campaign cost last_7_days": "$415.51"
                },
                {
                  "source": "yahoo",
                  "account_id": 90001,
                  "campaign_id": 53333,
                  "account_name": "brax-test-account",
                  "campaign_name": "brax-test-uk",
                  "campaign cost last_7_days": "$170.20"
                }
              ]
            }


## Run a Rule by ID [POST /rules/{rule_id}/run]

+ Parameters
    + `rule_id` (ID, required)

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)
    + Attributes (RuleRun)

    + Body

            {
              "status": "success",
              "message": "Job Created",
              "job_id": 36
            }




## Rule Job Status [/rules/jobs]

After running a rule, its running status can be checked to show confirm whether the desired changes have been made.

The status endpoint returns the status details of a job for running a rule, and the history endpoint returns a list of jobs currently running or that have run in the past.


### Job history [GET]

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)

    + Headers
    
            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes
        - `results` (array[RuleJob])
        - `pagination` (Pagination)

    + Body

            {
                "jobs": [
                    {
                        "id": 32,
                        "rule": {
                            "name": "Pause poor performing campaigns",
                            "type": "pause_campaign"
                        },
                        "stats": {
                            "total": 5,
                            "remaining": 5,
                            "successful": 0,
                            "failed": 0
                        },
                        "created_at": "2017-05-19T18:46:28+00:00",
                        "created_by": "Mark Simon"
                    },
                    {
                        "id": 33,
                        "rule": {
                            "name": "Pause low spending campaigns",
                            "type": "pause_campaign"
                        },
                        "stats": {
                            "total": 5,
                            "remaining": 5,
                            "successful": 0,
                            "failed": 0
                        },
                        "created_at": "2017-05-19T23:50:52+00:00",
                        "created_by": "Mark Simon"
                    },
                    {
                        "id": 34,
                        "rule": {
                            "name": "Pause poor performing ads",
                            "type": "pause_ad"
                        },
                        "stats": {
                            "total": 2,
                            "remaining": 2,
                            "successful": 0,
                            "failed": 0
                        },
                        "created_at": "2017-05-20T01:10:28+00:00",
                        "created_by": "Mark Simon"
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 3,
                    "total": 3
                }
            }



## Status by Job ID [GET /rules/jobs/{job_id}]

+ Parameters
    + `job_id` (ID, required)

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Response 200 (application/json)
    + Attributes
        + `job` (RuleStatus) - running status of the job

    + Body

            {
                "id": 35,
                "rule": {
                    "id": 132,
                    "name": "asdf",
                    "type": "pause_campaign",
                    "amount": null,
                    "conditions": [
                        {
                            "id": null,
                            "metric": "campaign.cost",
                            "operator": ">",
                            "value": "10",
                            "date_range": "last_7_days"
                        }
                    ],
                    "filters": [
                        {
                            "id": null,
                            "source": null,
                            "account_id": null,
                            "campaign_id": null
                        }
                    ],
                    "created_at": null,
                    "updated_at": null
                },
                "details": [
                    {
                        "source": "yahoo",
                        "account_id": 90001,
                        "campaign_id": 52222,
                        "account_name": "brax-test-account",
                        "campaign_name": "brax-test-us",
                        "campaign cost last_7_days": "$415.51"
                    },
                    {
                        "source": "yahoo",
                        "account_id": 90001,
                        "campaign_id": 53333,
                        "account_name": "brax-test-account",
                        "campaign_name": "brax-test-uk",
                        "campaign cost last_7_days": "$170.20"
                    }
                ],
                "created_at": "2017-05-26T22:58:19+00:00"
            }

# Group Users
Endpoints to manage users and user settings.

Users can be **administrator**s which enables creation of other users and adding integrations.

#### User <a name='User' />
Describes a Brax user




| Field             | Type                             | Example                   | Description                                     |
|:------------------|----------------------------------|---------------------------|-------------------------------------------------|
| **id**            | <a href='#ID'>ID</a>             | 234567                    | primary user identifier                         |
| **username**      | string                           | ivan                      | username                                        |
| **email**         | string                           | user@site.com             | user's email                                    |
| **confirmed**     | boolean                          | true                      | user's confirmed status                         |
| **administrator** | boolean                          | false                     | whether or not a user is an administrator       |
| **created_at**    | <a href='#DateTime'>DateTime</a> | 2017-01-01T00:12:34+00:00 | date and time the user was created in Brax      |
| **updated_at**    | <a href='#DateTime'>DateTime</a> | 2017-02-03T13:45:01+00:00 | date and time the user was last updated in Brax |


## Users [/users{?offset,limit}]

### List Users [GET]
List all users.

+ Request (application/json)
    + Headers

            Authorization:Basic {{basic_token}}
            Accept:application/json

+ Parameters
    + `offset` (Integer, optional) - starting index of the items to fetch
        + Default: 0
    + `limit` (Integer, optional) - maximum number of items to fetch - max: `100`
        + Default: 100


+ Response 200 (application/json)

    + Headers

            X-RateLimit-Limit:60
            X-RateLimit-Remaining:59
            X-Request-Id:25a4f2cc-08a6-4a46-be10-d4edcb7ca66b

    + Attributes

        - `results` (array[User])
        - `pagination` (Pagination)

    + Body

            {
              "results": [
                {
                  "id": "123",
                  "username": "test_user",
                  "email": "test_user@example.com",
                  "confirmed": true,
                  "administrator": false,
                  "created_at": "2016-01-01T00:53:09+00:00",
                  "updated_at": "2017-02-17T05:41:51+00:00"
                },
                {
                  "id": "124",
                  "username": "admin_user",
                  "email": "admin_user@example.com",
                  "confirmed": true,
                  "administrator": true,
                  "created_at": "2016-01-01T15:13:14+00:00",
                  "updated_at": "2017-05-11T15:14:48+00:00"
                }
              ],
              "pagination": {
                "offset": 0,
                "limit": 100,
                "count": 2,
                "total": 2
              }
            }

# Group Types

#### ID <a name='ID' />
Fields named **..._id** — an integer representing the primary identifier for the referenced object


#### SourceID <a name='SourceID' />
Fields named **source_..._id** — a string representation of the source's unique identifier for the referenced object


#### Integer <a name='Integer' />
Whole numbers such as `1`, `2`, `3`...


#### Decimal <a name='Decimal' />
Decimal or double numeric value, such as: `0.001`, or `3.14`



#### Date <a name='Date' />
Dates are specified in YYYY-MM-DD format. e.g. `2017-01-01`


#### DateTime <a name='DateTime' />
Date and time with timezone formatted according to ISO-8601, e.g. `2016-01-01T15:13:14+00:00`


#### DateRange <a name='DateRange' />
Date ranges are simply strings describing relative date ranges


| Value          | Description                |
|:---------------|----------------------------|
| `yesterday`    | yesterday                  |
| `last_2_days`  | two days ago and yesterday |
| `last_3_days`  | last three days            |
| `last_4_days`  | last four days             |
| `last_5_days`  | last five days             |
| `last_6_days`  | last six days              |
| `last_7_days`  | last seven days            |
| `last_14_days` | last fourteen days         |
| `last_30_days` | last thirty days           |

#### Duration <a name='Duration' />
Time durations specified in hours, minutes, and seconds, e.g. `00:02:34`


#### Url <a name='Url' />
A properly formatted URI string according to RFC 3986


# Data Structures

## Url (string) - a properly formatted URI string according to RFC 3986

## Date (string) - dates are specified in YYYY-MM-DD format. e.g. `2017-01-01`

## DateTime (string) - date and time with timezone formatted according to ISO-8601, e.g. `2016-01-01T15:13:14+00:00`

## Decimal (number) - decimal or double numeric value, such as: `0.001`, or `3.14`

## Integer (number) - whole numbers such as `1`, `2`, `3`...

## Duration (string) - time durations specified in hours, minutes, and seconds, e.g. `00:02:34`

## ID (Integer) - fields named **..._id** — an integer representing the primary identifier for the referenced object

## SourceID (string) - fields named **source_..._id** — a string representation of the source's unique identifier for the referenced object

## DateRange (enum) - date ranges are simply strings describing relative date ranges
- `yesterday` - yesterday
- `last_2_days` - two days ago and yesterday
- `last_3_days` - last three days
- `last_4_days` - last four days
- `last_5_days` - last five days
- `last_6_days` - last six days
- `last_7_days` - last seven days
- `last_14_days` - last fourteen days
- `last_30_days` - last thirty days

## CampaignStatus (enum) - running status for a campaign
- `active` - campaign is running
- `paused` - campaign has been paused
- `budget_limited` - campaign has met its budget
- `deleted` - campaign has been deleted

## Source (enum) - string representing an ad network
+ `outbrain` - Outbrain ([www.outbrain.com](//www.outbrain.com))
+ `taboola` - Taboola ([www.taboola.com](//www.taboola.com))
+ `revcontent` - Revcontent ([www.revcontent.com](//www.revcontent.com))
+ `yahoo` - Yahoo Gemini ([gemini.yahoo.com](//gemini.yahoo.com))
+ `content-ad` - Content.ad ([www.content.ad](//content.ad))

## RuleType (enum) - describes the type of rule, indicates what it affects and how
Starred rule types will have an **amount** specified in the rule.
- `pause_campaign` - Pause Campaigns
- `pause_ad` - Pause Ads
- `block_publisher` - Block Publishers
- `block_section` - Block Sections (Outbrain)
- `block_target` - Block Targets (Revcontent)
- `pause_ad_group` - Pause Ad Groups (Yahoo)
- `modify_bid_publisher` - Update Site Bid Modifiers *
- `multiply_bid_target` - Update Target Bids *
- `multiply_bid_campaign` - Update Campaign Bids *

## ReportingObject (enum) - entities that export reporting data
- `campaign` - Campaigns
- `ad` - Ads
- `publisher` - Publishers (Outbrain), Sites (Taboola), and Widgets (Revcontent)
- `section` - Sections (Outbrain)
- `target` - Targets (Revcontent)
- `ad_group` - Ad Groups (Yahoo)

## Metric (enum) - a string composed of an object and a metric separated by a dot
### Members
- (enum) - reporting object
  - `campaign`, `ad`, `publisher`, `target`, `section`, `ad_group`
- . - a literal dot separating the reporting object and metric field
- (enum) - metric field
  - `impressions`, `clicks`, `conversions`, `cost`, `ctr`, `ecpc`, `cpa`, `icr`
  - `sessions`, `pageviews`, `pageviews_per_session`, `bounce_rate`, `avg_session_duration`, `goal_1_completions`, `goal_2_completions`

### Sample
- `campaign.clicks` - Campaign clicks
- `target.ctr` - Target CTR


## Operator (enum)
- `<` - less than 
- `=` - equals
- `>` - greater than


## Rule (object)

### Properties
+ `id`: `986` (ID) - rule primary identifier
+ `name`: `Pause poor performaing ads` (string, required) - name of the rule
+ `type`: `pause_ad` (RuleType, required) - determines what actions are performed on which objects
+ `amount`: `1.2500` (Decimal, optional) - value or multiplier by which to modify existing bids or values; `null` if amount does not apply to this rule type
+ `conditions` (array[Condition], required) - criteria for matching
+ `filters` (array[Filter], required) - restrict search to source, account, or campaign level
+ `created_at`: `2017-01-21T08:02:43+00:00` (DateTime) - date and time the rule was created in Brax
+ `updated_at`: `2017-01-25T08:02:43+00:00` (DateTime) - date and time the rule was last updated in Brax


## Condition (object) - criteria required to match target objects, e.g. `campaign.cost` `<` `10` `last_7_days`

### Properties
+ `id`: `721` (ID) - condition primary identifier
+ `metric`: `campaign.cost` (Metric, required) - metric for input criteria
+ `operator`: `<` (Operator, required) - comparison operator to apply
+ `value`: `10` (Decimal, required) - expected value for comparison
+ `date_range`: `last_7_days` (DateRange, required) - reporting range to aggregate metrics
+ `start_date`: `2017-02-12` (Date) - start date for aggregating metrics (determined by **date_range**)
+ `end_date`: `2017-02-12` (Date) - end date for aggregating metrics (determined by **date_range**)


## Filter (object)

### Properties
+ `id`: 87 (ID) - filter primary identifier
+ `source`: taboola (Source) - restrict search to the given network
+ `account_id`: 96751 (ID) - restrict search to the given account
+ `campaign_id`: 452677 (ID) - restrict search to the given campaign

## Match (object)
+ `source`: yahoo (Source) - source of the affected object
+ `account_id`: 65437 (ID) - identifier of the account of the affected object
+ `campaign_id`: 34634 (ID) - identifier of the campaign to be affected
+ `account_name`: Selfserve_ACME (string) - name of the account of the affected object
+ `campaign_name`: my_first_campaign (string) - name of the affected campaign
+ *object metric1 range*: `$124.56` (string) - metric values of the affected objects for the given date range, e.g. `campaign cost last_7_days`
+ *object metric2 range*: `0.2843` (string) - metric values of the affected objects for the given date range, e.g. `campaign ctr last_7_days`

## RulePreview (object)
+ `rule` (Rule) - the rule being previewed
+ `matches` (array[Match]) - list of matched items to be affected by running the rule

## RuleRun (object)
+ `status`: success (string) - `success` if successful, `error` otherwise
+ `message`: Job Created (string) - a human-readable message
+ `job_id`: 94 (ID) - Job ID that can be used to poll running status

## RuleJob (object)
+ `id`: 32 (ID) - primary identifier for this job
+ `rule` (object) - short description of the running rule
    + `id`: 986 (ID, required) - rule primary identifier
    + `name`: Pause poor performing campaigns (string) - name of the rule
    + `type`: pause_campaign (RuleType) - type of the rule
+ `stats` (object) - aggregated details of the job's running status
    + `total`: 5 (Integer) - total action items
    + `remaining`: 5 (Integer) - action items remaining
    + `successful`: 0 (Integer) - action items that have completed successfully
    + `failed`: 0 (Integer) - action items that have failed
+ `created_at`: `2017-05-19T18:46:28+00:00` (DateTime) - when the job was initiated
+ `created_by`: Mark Simon (string) - name of the user who ran the rule


## RuleStatus (object)
+ `id`: 32 (ID) - primary identifier of the job
+ `created_at`: `2017-05-19T18:46:28+00:00` (DateTime) - when the job was initiated
+ `rule` (Rule) - snapshot of the rule at the time it was run
+ `details` (array[Match]) - the action items to be processed

## Pagination (object)

### Properties
+ `offset`: 0 (Integer) - starting index of the result set
+ `limit`: 100 (Integer) - maximum possible records in the result set / page size
+ `count`: 100 (Integer) - actual number of records in the result set
+ `total`: 984 (Integer) - total number of available records for the requested resource

## Account (object) - represents an account accessible at a network
+ `id`: 123 (ID, required) - primary identifier for the account
+ `source_account_id`: 0ad55ae47d03845 (SourceID) - source's unique identifier for the account
+ `source`: outbrain (Source) - name of the source
+ `name`: Selfserve_ACME (string) - name of the account
+ `created_at`: `2017-01-21T08:02:43+00:00` (DateTime) - date and time the account was created in Brax
+ `updated_at`: `2017-01-25T08:02:44+00:00` (DateTime) - date and time the account was last updated in Brax

## Ad (object) - represents an ad in a campaign
+ `source_account_id`: `ACME-Rockets-SC` (SourceID) - source's unique identifier for the account
+ `source_campaign_id`: 26465874 (SourceID) - source's unique campaign identifier
+ `source_ad_id`: 0214741 (SourceID) - source's unique ad identifier
+ `tracking_ad_id`: `e138da` (string) - identifier provided to the tracking code via `{{AD_ID}}` for ads pushed from Brax
+ `source`: taboola (Source) - name of the source
+ `title`: Brax helps you scale with the best (string) - ad title / headline
+ `url`: `https://brax.io/campaign-tagging-content-distribution/?utm_medium=_&utm_source=Revcontent&utm_content=1` (Url) - ad destination url
+ `image_url`: 'https://example.com/test_image_1.jpg' (Url) - ad image url
+ `enabled`: true (boolean) - ad enabled status
+ `status`: active (string) - ad status

## Campaign (object) - represents a campaign running on a network
+ `id`: 234567 (ID) - primary campaign identifier
+ `source_account_id`: acmecorporation (SourceID) - source's unique identifier for the account
+ `source_campaign_id`: 232145547 (SourceID) - source's unique campaign identifier
+ `source`: revcontent (Source) - name of the source
+ `name`: my_first_campaign (string) - campaign name
+ `start_at`: `2017-01-01T05:00:00+00:00` (DateTime) - campaign start datetime
+ `end_at`: `2017-01-31T05:00:00+00:00` (DateTime) - campaign end datetime
+ `enabled`: true (boolean) - campaign enabled status
+ `status`: active (CampaignStatus) - campaign status
+ `cpc`: 0.08 (Decimal) - the cost per click assigned to this campaign
+ `budget_amount`: 105.00 (Decimal) - the allotted budget for this campaign
+ `tracking_code`: utm_campaign={{CAMPAIGN}} (string) - tracking code used on ads within this campaign
+ `created_at`: `2016-12-30T23:18:42+00:00` (DateTime) - date and time the campaign was created in Brax
+ `updated_at`: `2017-01-25T08:02:43+00:00` (DateTime) - date and time the campaign was last updated in Brax


## User (object) - describes a Brax user
+ `id`: 234567 (ID) - primary user identifier
+ `username`: ivan (string) - username
+ `email`: user@site.com (string) - user's email
+ `confirmed`: true (boolean) - user's confirmed status
+ `administrator`: false (boolean) - whether or not a user is an administrator
+ `created_at`: `2017-01-01T00:12:34+00:00` (DateTime) - date and time the user was created in Brax
+ `updated_at`: `2017-02-03T13:45:01+00:00` (DateTime) - date and time the user was last updated in Brax



## ReportParams (object) - input parameters for pulling reporting data
+ `offset`: 0 (Integer) - starting index of the result set
+ `limit`: 100 (Integer) - maximum number of records to fetch; max: `100`
+ `source`: revcontent (Source) - name of the source
+ `source_account_id`: acmecompany (SourceID) - source's unique account identifier
+ `source_campaign_id`: 67890 (SourceID) - source's unique campaign identifier
+ `start_date`: `2017-02-12` (Date, required) - start date for aggregating metrics
+ `end_date`: `2017-02-18` (Date, required) - end date for aggregating metrics

## ReportingMetrics (object) - Results will contain these standard performance metrics
+ `impressions`: 21 (Integer) - impressions
+ `clicks`: 4 (Integer) - clicks
+ `conversions`: 2 (Integer) - conversions
+ `cost`: 1.09 (Decimal) - cost
+ `ctr`: 0.1905 (Decimal) - click through rate
+ `ecpc`: 0.2725 (Decimal) - estimated cost per click
+ `cpa`: 0.545 (Decimal) - cost per action
+ `icr`: 0.09523810 (Decimal) - impression:conversion rate

## GoogleAnalyticsMetrics (object) - For users with Google Analytics enabled, results will also contain these analytics metrics
+ `sessions`: 522 (Integer,optional) - sessions
+ `pageviews`: 3985 (Integer,optional) - pageviews
+ `pageviews_per_session`: 7.6341 (Decimal,optional) - pageviews per session
+ `bounce_rate`: 0.0249 (Decimal,optional) - bounce rate
+ `avg_session_duration`: 00:05:54 (Duration,optional) - average session suration
+ `goal_1_completions`: 1 (Integer,optional) - goal #1 completions
+ `goal_2_completions`: 68 (Integer,optional) - goal #2 completions

## AdsReport (object)
+ `source_account_id`: 0ad55ae47d03845 (SourceID) - source's unique identifier for the account
+ `source_campaign_id`: 0c631ab2384aaf5 (SourceID) - source's unique campaign identifier
+ `source_ad_id`: 0214741 (SourceID) - source's unique ad identifier
+ `tracking_ad_id`: e138da (string) - identifier provided to the tracking code via `{{AD_ID}}` for ads pushed from Brax
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## CampaignsReport (object)
+ `source_account_id`: 0ad55ae47d03845 (SourceID) - source's unique identifier for the account
+ `source_campaign_id`: 0c631ab2384aaf5 (SourceID) - source's unique campaign identifier
+ `name`: Content Scaling for Dummies (string) - name identifying campaign
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## AdGroupsReport (object)
+ `source_account_id`: 0ad55ae47d03845 (SourceID) - source's unique identifier for the account
+ `source_campaign_id`: 0c631ab2384aaf5 (SourceID) - source's unique campaign identifier
+ `source_ad_group_id`: 12345 (SourceID) - source's unique ad group identifier
+ `name`: Content Scaling for Dummies (string) - name identifying ad group
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## PublishersReport (object)
### Properties
+ `source_account_id`: 0ad55ae47d03845 (SourceID) - source's unique account identifier
+ `source_campaign_id`: 0c631ab2384aaf5 (SourceID) - source's unique campaign identifier
+ `source_publisher_id`: fba33dba5d44106 (SourceID) - source's unique publisher identifier
+ `name`: `Big News Site` (string) - name identifying publisher
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## SectionsReport (object)
### Properties
+ `source_account_id`: 0ad55ae47d03845 (SourceID) - source's unique account identifier
+ `source_campaign_id`: 0c631ab2384aaf5 (SourceID) - source's unique campaign identifier
+ `source_publisher_id`: fba33dba5d44106 (SourceID) - source's unique publisher identifier
+ `source_section_id`: fb3a3dba54d1460 (SourceID) - source's unique section identifier
+ `publisher_name`: `Big News Site` (string) - name identifying publisher 
+ `name`: `Booming News` (string) - name identifying section
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## TargetsReport (object)
### Properties
+ `source_account_id`: 12345 (SourceID) - source's unique account identifier
+ `source_campaign_id`: 67890 (SourceID) - source's unique campaign identifier
+ `source_target_id`: 74 (SourceID) - source's unique target identifier
+ `name`: `Tech and Gadgets` (string) - name identifying target 
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics
