# Group Accounts
Endpoints to manage accounts and account settings.

The Account object has the following properties:
...

## Accounts [/accounts{?offset,limit,source}]

+ Parameters
    :[](params/pagination.apib)
    :[](params/source.apib)

### List Accounts [GET]
List all accounts.

+ Request (application/json)
    + Headers

        :[](headers/basic.apib)

+ Response 200
    + Headers

        :[](headers/ratelimit.apib)

    + Attributes

        - `results` (array[Account])
        - `pagination` (Pagination)

    + Body

        :[](../json/accounts.json)


