# Group Ads
Endpoints to manage ads.

## Ads [/ads{?offset,limit,source,account_id,campaign_id}]

### List Ads [GET]
List all ads.

+ Parameters
    :[](params/pagination.apib)
    :[](params/source.apib)
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)

+ Request (application/json)
    + Headers

        :[](headers/basic.apib)

+ Response 200 
    + Headers

        :[](headers/ratelimit.apib)

    + Attributes

        - `results` (array[Ad])
        - `pagination` (Pagination)


    + Body
    
        :[](../json/ads.json)


