# Group Ads
Endpoints to manage ads.

## Ads [/ads{?offset,limit,source,account_id,campaign_id}]

### List Ads [GET]
List all ads.

+ Parameters
:[](params/pagination.apib)
:[](params/source.apib)
:[](params/source_account_id.apib)
:[](params/source_campaign_id.apib)

+ Request (application/json)
    + Headers

:[](headers/basic.apib)

+ Response 200 
    + Headers

:[](headers/ratelimit.apib)

    + Attributes (Ad)

    + Body
    
            {
              "results": [
                    {
                      "id": "1",
                      "vendor_campaign": "12345",
                      "vendor_ad": "342336233",
                      "title": "Brax automates the world",
                      "url": "https://brax.io/campaign-tagging-content-distribution/?utm_medium=_&utm_source=Revcontent&utm_content=1",
                      "image_url": "https://example.com/test_image_1.jpg",
                      "enabled": true,
                      "status": "paused"
                    },
                    {
                      "id": "2",
                      "vendor_campaign": "12345",
                      "vendor_ad": "342336234",
                      "title": "Brax automates the world",
                      "url": "https://brax.io/campaign-tagging-content-distribution/?utm_medium=_&utm_source=Revcontent&utm_content=2",
                      "image_url": "https://example.com/test_image_2.jpg",
                      "enabled": false,
                      "status": "rejected"
                    }
                ],
                "pagination": {
                    "offset": 0,
                    "limit": 100,
                    "count": 2,
                    "total": 2
                }
            }

