## Authentication [/accounts]
This API uses Basic Authentication for its authentication.

### Authentication Test [GET]

+ Request (application/json)

    + Headers

            :[](headers/basic.apib)

+ Response 200 (application/json)

    + Headers

            :[](headers/ratelimit.apib)

    + Body

            :[](../json/accounts.json)

+ Response 401 (application/json)

    + Headers
    
            :[](headers/ratelimit.apib)
    
    + Body
    
            {
                "timestamp": "2017-05-24 01:07:38",
                "message": "Invalid credentials",
                "errors": null
            }

+ Response 403 (application/json)

    + Headers
    
            :[](headers/ratelimit.apib)
    
    + Body
    
            {
                "timestamp": "2017-05-24 01:07:38",
                "message": "API access is not enabled",
                "errors": null
            }
            
