# Group Campaigns
Endpoints to manage campaigns and campaign settings.

The Campaign object has the following properties (common to all sources):

## Campaigns [/campaigns{?offset,limit,source,account_id,campaign_id}]

### List Campaigns [GET]
List all campaigns.

+ Parameters
:[](params/pagination.apib)
:[](params/source.apib)
:[](params/source_account_id.apib)
:[](params/source_campaign_id.apib)

+ Request (application/json)
    + Headers

:[](headers/basic.apib)


+ Response 200 

    + Headers

:[](headers/ratelimit.apib)

    + Attributes (Campaign)


