# Data Structures

## Url (string) - a properly formatted URI according to RFC 3986

## Date (string) - formatted date, such as: `2017-01-01`

## DateTime (string) - date time formatted according to ISO-8601, e.g. `2016-01-01T15:13:14+00:00`

## Decimal (number) - decimal or double numeric value, such as: `0.001`, or `3.14`

## Integer (number) - a whole number such as `1`, `2`, `3`...

## Duration (string) - a duration in hours, minutes, and seconds, e.g. `00:02:34`

## ID (Integer) - fields named **..._id** — the primary identifier for the referenced object

## SourceID (string) - fields named **source_..._id** — the source's unique identifier for the referenced object

## DateRange (enum) - string describing a relative date range
- `yesterday` - yesterday
- `last_2_days` - two days ago and yesterday
- `last_3_days` - last three days
- `last_4_days` - last four days
- `last_5_days` - last five days
- `last_6_days` - last six days
- `last_7_days` - last seven days
- `last_14_days` - last fourteen days
- `last_30_days` - last thirty days

## CampaignStatus (enum) - running status for a campaign
- `active` - campaign is running
- `paused` - campaign has been paused
- `budget_limited` - campaign has met its budget
- `deleted` - campaign has been deleted

## Source (enum) - string representing an ad network
+ `outbrain` - Outbrain ([www.outbrain.com](//www.outbrain.com))
+ `taboola` - Taboola ([www.taboola.com](//www.taboola.com))
+ `revcontent` - Revcontent ([www.revcontent.com](//www.revcontent.com))
+ `yahoo` - Yahoo Gemini ([gemini.yahoo.com](//gemini.yahoo.com))
+ `content-ad` - Content.ad ([www.content.ad](//content.ad))

## RuleType (enum) - string describing the type of rule, indicating what it affects and how
- `pause_campaign` - Pause Campaigns
- `pause_ad` - Pause Ads
- `block_publisher` - Block Publishers
- `block_section` - Block Sections (Outbrain)
- `block_target` - Block Targets (Revcontent)
- `pause_ad_group` - Pause Ad Groups (Yahoo)
- `modify_bid_publisher` - Update Site Bid Modifiers
- `multiply_bid_target` - Update Target Bids
- `multiply_bid_campaign` - Update Campaign Bids

## Metric (enum) - a string composed of an object and a metric separated by a dot
### Members
- `campaign`, `ad`, `publisher`, `target`, `section`, `ad_group` (enum) - reporting object
- .
- `impressions`, `clicks`, `conversions`, `cost`, `ctr`, `ecpc`, `cpa`, `icr`, `sessions`, `pageviews`, `pageviews_per_session`, `bounce_rate`, `avg_session_duration`, `goal_1_completions`, `goal_2_completions` (enum) - metric field

### Sample
- `campaign.clicks` - Campaign clicks
- `target.ctr` - Target CTR


## Operator (enum)
- `<` - less than 
- `=` - equals
- `>` - greater than


## Rule (object)

### Properties
+ `id`: 986 (ID, required) - rule primary identifier
+ `name`: my ads rule (string, required) - name of the rule
+ `type`: `pause_ad` (RuleType, required) - determines what actions are performed on which objects
+ `conditions` (array[Condition], required) - criteria for matching
+ `filters` (array[Filter], required) - restrict search to source, account, or campaign level


## Condition (object) - criteria required to match target objects, e.g. `campaign.cost` `<` `10` `last_7_days`

### Properties
+ `id`: 721 (ID, required) - condition primary identifier
+ `metric`: `campaign.cost` (Metric, required) - metric for input criteria
+ `operator`: `<` (Operator, required) - comparison operator to apply
+ `value`: 10 (Decimal, required) - expected value for comparison
+ `date_range`: `last_7_days` (DateRange, required) - reporting range to aggregate metrics


## Filter (object)

### Properties
+ `id`: 87 (ID, required) - filter primary identifier
+ `source`: taboola (Source, optional) - restrict search to the given network
+ `account_id`: 96751 (ID, optional) - restrict search to the given account
+ `campaign_id`: 452677 (ID, optional) - restrict search to the given campaign

## Match (object)
+ `source`: yahoo (Source) - source of the affected object
+ `account_id`: 65437 (ID) - identifier of the account of the affected object
+ `campaign_id`: 34634 (ID) - identifier of the campaign to be affected
+ `account_name`: brax-test-account (string) - name of the account of the affected object
+ `campaign_name`: brax-test-campaign (string) - name of the affected campaign
+ *object metric1 range*: `$124.56` (string) - metric values of the affected objects for the given date range, e.g. `campaign cost last_7_days`
+ *object metric2 range*: `0.2843` (string) - metric values of the affected objects for the given date range, e.g. `campaign ctr last_7_days`

## RulePreview (object)
+ `rule` (Rule) - the rule being previewed
+ `matches` (array[Match]) - list of matched items to be affected by running the rule

## RuleRun (object)
+ `status`: success (string) - `success` if successful, `error` otherwise
+ `message`: Job Created (string) - a human-readable message
+ `job_id`: 94 (ID) - Job ID that can be used to poll running status

## RuleJob (object)
+ `id`: 32 (ID) - primary identifier for this job
+ `created_at`: 2017-05-19T18:46:28+00:00 (DateTime) - when the job was initiated
+ `created_by`: Mark Simon (string) - name of the user who ran the rule
+ `rule` (object) - short description of the running rule
    + `name`: my campaign rule (string) - name of the rule
    + `type`: pause_campaign (RuleType) - type of the rule
+ `stats` (object) - aggregated details of the job's running status
    + `total`: 5 (Integer) - total action items
    + `remaining`: 5 (Integer) - action items remaining
    + `successful`: 0 (Integer) - action items that have completed successfully
    + `failed`: 0 (Integer) - action items that have failed


## RuleStatus (object)
+ `id`: 32 (ID) - primary identifier of the job
+ `created_at`: 2017-05-19T18:46:28+00:00 (DateTime) - when the job was initiated
+ `rule` (Rule) - snapshot of the rule at the time it was run
+ `details` (array[Match]) - the action items to be processed

## Pagination (object) - indicates the number of records available

### Properties
+ `offset`: 0 (Integer) - starting index of the result set
+ `limit`: 100 (Integer) - maximum possible records in the result set / page size
+ `count`: 100 (Integer) - actual number of records in the result set
+ `total`: 984 (Integer) - total number of available records for the requested resource

## Account (object) - represents an account accessible at a network
+ `id`: 123 (ID, required) - primary identifier for the account
+ `source_account_id`: 782415 (SourceID) - source's unique identifier for the account
+ `source`: content-ad (Source) - name of the source
+ `name`: Selfserve_test_1 (string) - name of the account
+ `created_at`: 2017-01-21T08:02:43+00:00 (DateTime) - date and time the account was created
+ `updated_at`: 2017-01-25T08:02:43+00:00 (DateTime) - date and time the account was last updated

## Ad (object) - represents an ad in a campaign 
+ `source_campaign_id` (SourceID) - source's unique campaign identifier
+ `source_ad_id` (SourceID) - source's unique ad identifier
+ `tracking_ad_id` (string) - identifier provided to the tracking code via `{{AD_ID}}` for ads pushed from Brax
+ `title` (string) - ad title / headline
+ `url` (Url) - ad destination url
+ `image_url` (Url) - ad image url
+ `enabled` (boolean) - ad enabled status
+ `status` (string) - ad status       

## Campaign (object) - represents a campaign running on a network
+ `id`: 234567 (ID) - primary campaign identifier
+ `source_campaign_id`: 9862145 (SourceID) - source's unique campaign identifier
+ `source`: revcontent (Source) - name of the source
+ `name`: my-test-campaign (string) - campaign name
+ `start_at`: 2017-01-01T05:00:00+00:00 (DateTime) - campaign start datetime
+ `end_at`:  2017-01-31T05:00:00+00:00 (DateTime) - campaign end datetime
+ `enabled`: true (boolean) - campaign enabled status
+ `status`: active (CampaignStatus) - campaign status
+ `cpc`: 0.08 (Decimal) - the cost per click assigned to this campaign
+ `budget_amount`: 105.00 (Decimal) - the allotted budget for this campaign
+ `tracking_code`: utm_campaign={{CAMPAIGN}} (string) - tracking code used on ads within this campaign
+ `created_at`: 2016-12-30T23:18:42+00:00 (DateTime) - date and time the campaign was created
+ `updated_at`: 2017-01-25T08:02:43+00:00 (DateTime) - date and time the campaign was last updated


## User (object) - describes a Brax user
+ `id`: 234567 (ID) - primary user identifier
+ `username`: ivan (string) - username
+ `email`: user@site.com (string) - user's email
+ `confirmed`: true (boolean) - user's confirmed status
+ `administrator`: false (boolean) - whether or not a user is an administrator
+ `created_at`: 2017-01-01T00:12:34+00:00 (DateTime) - date and time the user was created
+ `updated_at`: 2017-02-03T13:45:01+00:00 (DateTime) - date and time the user was last updated



## ReportParams (object) - input parameters for pulling reporting data
+ `offset`: 0 (Integer) - starting index of the result set
+ `limit`: 100 (Integer) - maximum number of records to fetch; max: `100`
+ `source`: revcontent (Source) - name of the source
+ `source_account_id`: 12345 (SourceID) - source's unique account identifier
+ `source_campaign_id`: 67890 (SourceID) - source's unique campaign identifier
+ `start_date`: 2017-02-12 (Date, required) - start date for aggregating metrics
+ `end_date`: 2017-02-18 (Date, required) - end date for aggregating metrics

## ReportingMetrics (object) - Results will contain these standard performance metrics
+ `impressions`: 21 (Integer) - impressions
+ `clicks`: 4 (Integer) - clicks
+ `conversions`: 2 (Integer) - conversions
+ `cost`: 1.09 (Decimal) - cost
+ `ctr`: 0.1905 (Decimal) - click through rate
+ `ecpc`: 0.2725 (Decimal) - estimated cost per click
+ `cpa`: 0.545 (Decimal) - cost per action
+ `icr`: 0.09523810 (Decimal) - impression:conversion rate

## GoogleAnalyticsMetrics (object) - For users with Google Analytics enabled, results will also contain these analytics metrics
+ `sessions`: 522 (Integer,optional) - sessions
+ `pageviews`: 3985 (Integer,optional) - pageviews
+ `pageviews_per_session`: 7.6341 (Decimal,optional) - pageviews per session
+ `bounce_rate`: 0.0249 (Decimal,optional) - bounce rate
+ `avg_session_duration`: 00:05:54 (Duration,optional) - average session suration
+ `goal_1_completions`: 1 (Integer,optional) - goal #1 completions
+ `goal_2_completions`: 68 (Integer,optional) - goal #2 completions

## AdsReport (object)
+ `source_account_id` (SourceID) - source's unique account identifier
+ `source_campaign_id` (SourceID) - source's unique campaign identifier
+ `source_ad_id` (SourceID) - source's unique ad identifier
+ `tracking_ad_id` (string) - identifier provided to the tracking code via `{{AD_ID}}` for ads pushed from Brax
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## CampaignsReport (object)
+ `source_account_id` (SourceID) - source's unique account identifier
+ `source_campaign_id` (SourceID) - source's unique campaign identifier
+ `name` (string) - name identifying campaign
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## AdGroupsReport (object)
+ `source_account_id` (SourceID) - source's unique account identifier
+ `source_campaign_id` (SourceID) - source's unique campaign identifier
+ `source_ad_group_id` (SourceID) - source's unique ad group identifier
+ `name` (string) - name identifying ad group
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## PublishersReport (object)
### Properties
+ `source_account_id` (SourceID) - source's unique account identifier
+ `source_campaign_id` (SourceID) - source's unique campaign identifier
+ `source_publisher_id`: "00a4cb19d55ea630d69fba33dba5d44106" (SourceID) - source's unique publisher identifier
+ `name`: "Test Publisher" (string) - name identifying publisher
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## SectionsReport (object)
### Properties
+ `source_account_id` (SourceID) - source's unique account identifier
+ `source_campaign_id` (SourceID) - source's unique campaign identifier
+ `source_publisher_id`: "00a4cb19d55ea630d69fba33dba5d44106" (SourceID) - source's unique publisher identifier
+ `source_section_id`: "00a4cb1d955ea603d69fb3a3dba54d1460" (SourceID) - source's unique section identifier
+ `publisher_name`: "Test Publisher" (string) - name identifying publisher 
+ `name`: "Test Section" (string) - name identifying section
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

## TargetsReport (object)
### Properties
+ `source_account_id` (SourceID) - source's unique account identifier
+ `source_campaign_id` (SourceID) - source's unique campaign identifier
+ `source_target_id`: (SourceID) - source's unique target identifier
+ `name`: "Test Target" (string) - name identifying target 
+ Include ReportingMetrics
+ Include GoogleAnalyticsMetrics

