## Example [/ping]
In this document, you can click links that look like the one below to get a full description and an example of the request and response for the given endpoint.

### Ping Test [GET]
This is a sanity check when all else fails.

+ Request (application/json)

    + Headers

            Accept:application/json

+ Response 200 (application/json)

    + Headers

            :[](headers/ratelimit.apib)

    + Body

            {
                "results": "pong"
            }

