## Example [/ping]
This is a sanity check when all else fails.

### Ping Test [GET]

+ Request (application/json)

    + Headers

            Accept:application/json

+ Response 200 (application/json)

    + Headers

            :[](headers/ratelimit.apib)

    + Body

            {
                "results": "pong"
            }

