FORMAT: 1A
HOST: https://api.brax.io

# BRAX Console API 1.0
Brax Console API 1.0

# Postman
Feel free to take advantage of our Postman collection here: [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/ff73088700e24511e68a)
