# Group Reporting
Endpoints for managing reporting of ads, ad groups, campaigns, publishers, sections, and targets.

# Requests and responses
All reporting endpoints accept a combination of parameters to refine the result set.

:[](tables/ReportParams.apib)

:[](tables/ReportingMetrics.apib)

:[](tables/GoogleAnalyticsMetrics.apib)


## Ad Reports [/reports/ads{?offset,limit,source,source_account_id,start_date,end_date}]

### Ads [GET]
Fetch ads report for a source and **account_id**.

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: "content-ad"
    :[](params/source_account_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers
    
        :[](headers/basic.apib)


+ Response 200 (application/json)

    + Headers

        :[](headers/ratelimit.apib)

    + Attributes
    
        + `results` (array[AdsReport])
        + `pagination` (Pagination)

    + Body

            :[](../json/ads_report.json)


## Ad Groups Report [/reports/ad-groups{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

### Ad Groups [GET]
Fetch ad groups report for a **source** and **source_account_id**; optionally with **source_campaign_id**.

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: "yahoo"
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

        :[](headers/basic.apib)

+ Response 200 (application/json)

    + Headers

        :[](headers/ratelimit.apib)

    + Attributes
    
        - `results` (array[AdGroupsReport])
        - `pagination` (Pagination)

    + Body

            :[](../json/ad_groups_report.json)


## Campaigns Report [/reports/campaigns{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

### Campaigns [GET]
Fetch campaigns report for a **source** and **source_account_id**; optionally with **source_campaign_id**.

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: "outbrain"
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

        :[](headers/basic.apib)

+ Response 200 (application/json)

    + Headers

        :[](headers/ratelimit.apib)

    + Attributes
    
        - `results` (array[CampaignsReport])
        - `pagination` (Pagination)

    + Body
    
            :[](../json/campaigns_report.json)


## Publishers Report [/reports/publishers{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

### Publishers [GET]
Fetch publishers report for a **source** and **source_account_id**; optionally with **source_campaign_id**.

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: "taboola"
    :[](params/source.apib)
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

        :[](headers/basic.apib)




+ Response 200 (application/json)
    + Headers

        :[](headers/ratelimit.apib)
    
    + Attributes

        - `results` (array[PublishersReport])
        - `pagination` (Pagination)

    + Body

            :[](../json/publishers_report.json)


## Sections Report [/reports/sections{?offset,limit,source,account_id,source_campaign_id,start_date,end_date}]

### Sections [GET]
Fetch sections report for a source and **account_id**; optionally with **source_campaign_id**.

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: "outbrain"
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

        :[](headers/basic.apib)



+ Response 200 (application/json)
    + Headers

        :[](headers/ratelimit.apib)
    
    + Attributes

        - `results` (array[SectionsReport])
        - `pagination` (Pagination)

    + Body

            :[](../json/sections_report.json)



## Targets Report [/reports/targets{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

### Targets [GET]
Fetch targets report for a **source** and **source_account_id**; optionally with **source_campaign_id**.

+ Parameters
    :[](params/pagination.apib)
    + `source`: "revcontent" (Source, optional) - source name
        + Sample: "revcontent"
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

        :[](headers/basic.apib)


+ Response 200 (application/json)
    + Headers

        :[](headers/ratelimit.apib)
    
    + Attributes

        - `results` (array[SectionsReport])
        - `pagination` (Pagination)

    + Body

            :[](../json/targets_report.json)

