# Group Reporting

Performance data can be accessed via endpoints given a date range and filtering parameters.

We will describe the parmeters availalbe for requests and responses, and then list the endpoints below.

# Requests and responses
All reporting endpoints accept a combination of parameters to refine the result set.

:[](tables/ReportParams.apib)

:[](tables/ReportingMetrics.apib)

:[](tables/GoogleAnalyticsMetrics.apib)


## Reporting Endpoints [/reports]
Reports can be fetched for a **source** and **source_account_id**; optionally with **source_campaign_id**.

These are the objects that provide performance data:

:[](tables/ReportingObject.apib)

### Ads Report [GET /reports/ads{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: content-ad
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers
    
            :[](headers/basic.apib)


+ Response 200 (application/json)

    + Headers

            :[](headers/ratelimit.apib)

    + Attributes
    
        + `results` (array[AdsReport])
        + `pagination` (Pagination)

    + Body

            :[](../json/ads_report.json)

### Ad Groups Report [GET /reports/ad-groups{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: yahoo
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)

+ Response 200 (application/json)

    + Headers

            :[](headers/ratelimit.apib)

    + Attributes
    
        - `results` (array[AdGroupsReport])
        - `pagination` (Pagination)

    + Body

            :[](../json/ad_groups_report.json)


### Campaigns Report [GET /reports/campaigns{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: outbrain
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)

+ Response 200 (application/json)

    + Headers

            :[](headers/ratelimit.apib)

    + Attributes
    
        - `results` (array[CampaignsReport])
        - `pagination` (Pagination)

    + Body
    
            :[](../json/campaigns_report.json)


### Publishers Report [GET /reports/publishers{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    :[](params/pagination.apib)
    :[](params/source.apib)
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)


+ Response 200 (application/json)
    + Headers

            :[](headers/ratelimit.apib)
    
    + Attributes

        - `results` (array[PublishersReport])
        - `pagination` (Pagination)

    + Body

            :[](../json/publishers_report.json)


### Sections Report [GET /reports/sections{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    :[](params/pagination.apib)
    + `source` (Source, optional) - source name
        + Sample: outbrain
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)



+ Response 200 (application/json)
    + Headers

            :[](headers/ratelimit.apib)
    
    + Attributes

        - `results` (array[SectionsReport])
        - `pagination` (Pagination)

    + Body

            :[](../json/sections_report.json)


## Targets Report [GET /reports/targets{?offset,limit,source,source_account_id,source_campaign_id,start_date,end_date}]

+ Parameters
    :[](params/pagination.apib)
    + `source`: (Source, optional) - source name
        + Sample: revcontent
    :[](params/source_account_id.apib)
    :[](params/source_campaign_id.apib)
    :[](params/start_end_dates.apib)

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)


+ Response 200 (application/json)
    + Headers

            :[](headers/ratelimit.apib)
    
    + Attributes

        - `results` (array[TargetsReport])
        - `pagination` (Pagination)

    + Body

            :[](../json/targets_report.json)

