# Group Rules
Endpoints to manage rules, rule settings, preview running rules, run rules, and rule job statuses.

:[](tables/Rule.apib)
:[](tables/Condition.apib)
:[](tables/Filter.apib)
:[](tables/RuleType.apib)

## Rules [/rules{?offset,limit}]

### List Rules [GET]
List all rules.

+ Parameters
    :[](params/pagination.apib)

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)



+ Response 200 (application/json)

    + Headers

            :[](headers/ratelimit.apib)

    + Attributes
        + `results` (array[Rule])
        + `pagination` (Pagination)

    + Body

            :[](../json/rules.json)


## Get a Rule by ID [/rules/{rule_id}]
Show the configuration of a single rule by ID

+ Parameters
    + `rule_id` (ID, required)

### Rule by ID [GET]

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)

+ Response 200 (application/json)
    + Attributes (Rule)

    + Body

            :[](../json/rules_by_id.json)


## Rules Preview By Rule Id [/rules/{rule_id}/preview]
Shows the potential result of running a rule, including the current rule settings, and the affected objects.

Rule previews have the following structure...
:[](tables/RulePreview.apib)
:[](tables/Match.apib)

Depending on how a rule is configured, there will be multiple object metrics shown in the response. The field names will contain spaces for these metrics.

+ Parameters
    + `rule_id` (ID, required)

### Preview running a rule [GET]

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)

+ Response 200 (application/json)
    + Attributes (RulePreview)

    + Body

            :[](../json/rule_preview.json)


## Run a Rule by ID [/rules/{rule_id}/run]
A POST request send to this endpoint will enqueue the running of the specified rule with the default match items selected,
and return a response with the `job_id` of the job which can be queried via the status endpoint below.

+ Parameters
    + `rule_id` (ID, required)

### Run a rule [POST]

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)

+ Response 200 (application/json)
    + Attributes (RuleRun)

    + Body

            :[](../json/rule_run.json)




## Rule History [/rules/jobs]

### Job history [GET]
Returns a list of jobs currently running or that have run in the past.

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)

+ Response 200 (application/json)

    + Headers
    
            :[](headers/ratelimit.apib)

    + Attributes
        - `results` (array[RuleJob])
        - `pagination` (Pagination)

    + Body

            :[](../json/rule_jobs.json)


## Rules Job Status Job ID [/rules/jobs/{job_id}]
Returns the status details of a job for running a rule.

+ Parameters
    + `job_id` (ID, required)

### Job status by Job ID [GET]

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)

+ Response 200 (application/json)
    + Attributes
        + `job` (RuleStatus) - running status of the job

    + Body

            :[](../json/rule_status.json)

