# Group Types

:[](tables/ID.apib)
:[](tables/SourceID.apib)
:[](tables/PublisherID.apib)
:[](tables/Integer.apib)
:[](tables/Decimal.apib)

:[](tables/Date.apib)
:[](tables/DateTime.apib)
:[](tables/DateRange.apib)
:[](tables/Duration.apib)
:[](tables/Url.apib)
