# Group Users
Endpoints to manage users and user settings.

Users can be **administrator**s which enables creation of other users and adding integrations.

:[](tables/User.apib)

## Users [/users{?offset,limit}]

### List Users [GET]
List all users.

+ Request (application/json)
    + Headers

            :[](headers/basic.apib)

+ Parameters
    :[](params/pagination.apib)


+ Response 200 (application/json)

    + Headers

            :[](headers/ratelimit.apib)

    + Attributes

        - `results` (array[User])
        - `pagination` (Pagination)

    + Body

            :[](../json/users.json)

