# Account <a name='Account' />
Represents an account accessible at a network

| Field               | Type                             | Example                              | Description                                |
|:--------------------|----------------------------------|--------------------------------------|--------------------------------------------|
| `id`                | <a href='#ID'>ID</a> required    | 123                                  | primary identifier for the account         |
| `source`            | <a href='#Source'>Source</a>     |                                      | name of the source                         |
| `source_account_id` | <a href='#SourceID'>SourceID</a> | "e010f3346de2e41fed1a288a3ba5cd5e29" | source's unique identifier for the account |
| `name`              | string                           | "Selfserve_test_1"                   | name of the account                        |
| `created_at`        | <a href='#DateTime'>DateTime</a> |                                      | date and time the account was created      |
| `updated_at`        | <a href='#DateTime'>DateTime</a> |                                      | date and time the account was last updated |

