# Account
- represents an account accessible at a network

| Field                | Type                                            | Comments                                   |
|:---------------------|-------------------------------------------------|--------------------------------------------|
| `id`:                | 123 (ID, required)                              | primary identifier for the account         |
| `source`             | (Source)                                        | name of the source                         |
| `source_account_id`: | "e010f3346de2e41fed1a288a3ba5cd5e29" (SourceID) | source's unique identifier for the account |
| `name`:              | "Selfserve_test_1" (string)                     | name of the account                        |
| `created_at`         | (DateTime)                                      | date and time the account was created      |
| `updated_at`         | (DateTime)                                      | date and time the account was last updated |

