#### Account <a name='Account' />
Represents an account accessible at a network

| Field                 | Type                             | Example          | Description                                |
|:----------------------|----------------------------------|------------------|--------------------------------------------|
| **id**                | <a href='#ID'>ID</a> *required*  | 123              | primary identifier for the account         |
| **source**            | <a href='#Source'>Source</a>     | content-ad       | name of the source                         |
| **source_account_id** | <a href='#SourceID'>SourceID</a> | 782415           | source's unique identifier for the account |
| **name**              | string                           | Selfserve_test_1 | name of the account                        |
| **created_at**        | <a href='#DateTime'>DateTime</a> |                  | date and time the account was created      |
| **updated_at**        | <a href='#DateTime'>DateTime</a> |                  | date and time the account was last updated |

