# Ad <a name='Ad' />
Represents an ad in a campaign 

| Field                | Type                             | Example | Description                                                 |
|:---------------------|----------------------------------|---------|-------------------------------------------------------------|
| `tracking_ad_id`     | string                           |         | identifier provided to the ad's tracking code via {{AD_ID}} |
| `source_campaign_id` | <a href='#SourceID'>SourceID</a> |         | unique vendor_campaign identifier                           |
| `source_ad_id`       | <a href='#SourceID'>SourceID</a> |         | vendor_ad id                                                |
| `title`              | string                           |         | ad title / headline                                         |
| `url`                | <a href='#Url'>Url</a>           |         | ad destination url                                          |
| `image_url`          | <a href='#Url'>Url</a>           |         | ad image url                                                |
| `enabled`            | boolean                          |         | ad enabled status                                           |
| `status`             | string                           |         | ad status                                                   |

