# Ad
- represents an ad in a campaign 

| Field                | Type       | Comments                                                    |
|:---------------------|------------|-------------------------------------------------------------|
| `tracking_ad_id`     | (string)   | identifier provided to the ad's tracking code via {{AD_ID}} |
| `source_campaign_id` | (SourceID) | unique vendor_campaign identifier                           |
| `source_ad_id`       | (SourceID) | vendor_ad id                                                |
| `title`              | (string)   | ad title / headline                                         |
| `url`                | (Url)      | ad destination url                                          |
| `image_url`          | (Url)      | ad image url                                                |
| `enabled`            | (boolean)  | ad enabled status                                           |
| `status`             | (string)   | ad status                                                   |

