#### Ad <a name='Ad' />
Represents an ad in a campaign 

| Field                  | Type                             | Description                                                                       |
|:-----------------------|----------------------------------|-----------------------------------------------------------------------------------|
| **tracking_ad_id**     | string                           | identifier provided to the tracking code via `{{AD_ID}}` for ads pushed from Brax |
| **source_campaign_id** | <a href='#SourceID'>SourceID</a> | source's unique campaign identifier                                               |
| **source_ad_id**       | <a href='#SourceID'>SourceID</a> | source's unique ad identifier                                                     |
| **title**              | string                           | ad title / headline                                                               |
| **url**                | <a href='#Url'>Url</a>           | ad destination url                                                                |
| **image_url**          | <a href='#Url'>Url</a>           | ad image url                                                                      |
| **enabled**            | boolean                          | ad enabled status                                                                 |
| **status**             | string                           | ad status                                                                         |

