#### AdsReport <a name='AdsReport' />


| Field                  | Type                                                         | Description                         |
|:-----------------------|--------------------------------------------------------------|-------------------------------------|
| **source_account_id**  | <a href='#SourceID'>SourceID</a>                             | source's unique account identifier  |
| **source_campaign_id** | <a href='#SourceID'>SourceID</a>                             | source's unique campaign identifier |
| **source_ad_id**       | <a href='#SourceID'>SourceID</a>                             | source's unique ad identifier       |
| **title**              | string                                                       | ad title / headline                 |
| **url**                | <a href='#Url'>Url</a>                                       | ad destination url                  |
| **image_url**          | <a href='#Url'>Url</a>                                       | ad image url                        |
| Include                | <a href='#ReportingMetrics'>ReportingMetrics</a>             |                                     |
| Include                | <a href='#GoogleAnalyticsMetrics'>GoogleAnalyticsMetrics</a> |                                     |

