# AdsReport

| Field                | Type                   | Comments                            |
|:---------------------|------------------------|-------------------------------------|
| `source_account_id`  | (string)               | source's unique account identifier  |
| `source_campaign_id` | (string)               | source's unique campaign identifier |
| `source_ad_id`       | (string)               | source's unique ad identifier       |
| `name`               | (string)               | name identifying ad                 |
| Include              | ReportingMetrics       |                                     |
| Include              | GoogleAnalyticsMetrics |                                     |

