# Campaign

| Field                | Type                | Comments                                       |
|:---------------------|---------------------|------------------------------------------------|
| `id`                 | (ID)                | primary campaign identifier                    |
| `source`:            | "outbrain" (Source) | name of the source                             |
| `source_campaign_id` | (SourceID)          | unique vendor_campaign identifier              |
| `name`               | (string)            | campaign name                                  |
| `start_at`           | (DateTime)          | campaign start datetime                        |
| `end_at`             | (DateTime)          | campaign end datetime                          |
| `enabled`            | (boolean)           | campaign enabled status                        |
| `status`             | (CampaignStatus)    | campaign status                                |
| `cpc`                | (Decimal)           | the cost per click assigned to this campaign   |
| `budget_amount`      | (Decimal)           | the allotted budget for this campaign          |
| `tracking_code`      | (string)            | tracking code used on ads within this campaign |
| `created_at`         | (DateTime)          | date and time the campaign was created         |
| `updated_at`         | (DateTime)          | date and time the campaign was last updated    |

