# CampaignStatus
- running status for a campaign

| Field            | Type| Comments                    |
|:-----------------|--|-----------------------------|
| `active`         |  | campaign is running         |
| `paused`         |  | campaign has been paused    |
| `budget_limited` |  | campaign has met its budget |
| `deleted`        |  | campaign has been deleted   |

