#### CampaignsReport <a name='CampaignsReport' />


| Field                  | Type                                                         | Description                         |
|:-----------------------|--------------------------------------------------------------|-------------------------------------|
| **source_account_id**  | <a href='#SourceID'>SourceID</a>                             | source's unique account identifier  |
| **source_campaign_id** | <a href='#SourceID'>SourceID</a>                             | source's unique campaign identifier |
| **name**               | string                                                       | name identifying campaign           |
| Include                | <a href='#ReportingMetrics'>ReportingMetrics</a>             |                                     |
| Include                | <a href='#GoogleAnalyticsMetrics'>GoogleAnalyticsMetrics</a> |                                     |

