#### CampaignStatus <a name='CampaignStatus' />
Running status for a campaign


| Value            | Description                 |
|:-----------------|-----------------------------|
| `active`         | campaign is running         |
| `paused`         | campaign has been paused    |
| `budget_limited` | campaign has met its budget |
| `deleted`        | campaign has been deleted   |

