# Condition <a name='Condition' />

| Field        | Type                                        | Example | Description |
|:-------------|---------------------------------------------|---------|-------------|
| `id`         | <a href='#Integer'>Integer</a> required     |         |             |
| `metric`     | <a href='#Metric'>Metric</a> required       |         |             |
| `operator`   | <a href='#Operator'>Operator</a> required   |         |             |
| `value`      | <a href='#Decimal'>Decimal</a> required     |         |             |
| `date_range` | <a href='#DateRange'>DateRange</a> required |         |             |

