# Condition

| Field        | Type                  | Comments|
|:-------------|-----------------------|--|
| `id`         | (Integer, required)   |  |
| `metric`     | (Metric, required)    |  |
| `operator`   | (Operator, required)  |  |
| `value`      | (Decimal, required)   |  |
| `date_range` | (DateRange, required) |  |

