# DateRange <a name='DateRange' />
String describing a relative date range

| Value          | Description                |
|:---------------|----------------------------|
| `yesterday`    | yesterday                  |
| `last_2_days`  | two days ago and yesterday |
| `last_3_days`  | last three days            |
| `last_4_days`  | last four days             |
| `last_5_days`  | last five days             |
| `last_6_days`  | last six days              |
| `last_7_days`  | last seven days            |
| `last_14_days` | last fourteen days         |
| `last_30_days` | last thirty days           |

