# Filter <a name='Filter' />

| Field         | Type                                  | Example | Description                           |
|:--------------|---------------------------------------|---------|---------------------------------------|
| `id`          | <a href='#ID'>ID</a> required         | 87      |                                       |
| `source`      | <a href='#Source'>Source</a> optional | taboola | restrict search to the given network  |
| `account_id`  | <a href='#ID'>ID</a> optional         | 96751   | restrict search to the given account  |
| `campaign_id` | <a href='#ID'>ID</a> optional         | 452677  | restrict search to the given campaign |

