# Filter

| Field         | Type                | Comments|
|:--------------|---------------------|--|
| `id`:         | 87 (ID, required)   |  |
| `source`      | (Source, required)  |  |
| `account_id`  | (Integer, required) |  |
| `campaign_id` | (Integer, required) |  |

