#### GoogleAnalyticsMetrics <a name='GoogleAnalyticsMetrics' />
For users with Google Analytics enabled, results will also contain these analytics metrics


| Field                     | Type                                        | Example  | Description              |
|:--------------------------|---------------------------------------------|----------|--------------------------|
| **sessions**              | <a href='#Integer'>Integer</a> *optional*   | 522      | sessions                 |
| **pageviews**             | <a href='#Integer'>Integer</a> *optional*   | 3985     | pageviews                |
| **pageviews_per_session** | <a href='#Decimal'>Decimal</a> *optional*   | 7.6341   | pageviews per session    |
| **bounce_rate**           | <a href='#Decimal'>Decimal</a> *optional*   | 0.0249   | bounce rate              |
| **avg_session_duration**  | <a href='#Duration'>Duration</a> *optional* | 00:05:54 | average session suration |
| **goal_1_completions**    | <a href='#Integer'>Integer</a> *optional*   | 1        | goal #1 completions      |
| **goal_2_completions**    | <a href='#Integer'>Integer</a> *optional*   | 68       | goal #2 completions      |

