#### Metric <a name='Metric' />
A string composed of an object and a metric separated by a dot




| Value             | Type                                                                                                                                                                                                    | Description      |
|:------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------|
| `campaign`,       | `ad` *`publisher`, `target`, `section`, `ad_group` enum*                                                                                                                                                | reporting object |
| .                 |                                                                                                                                                                                                         |                  |
| `impressions`,    | `clicks` *`conversions`, `cost`, `ctr`, `ecpc`, `cpa`, `icr`, `sessions`, `pageviews`, `pageviews_per_session`, `bounce_rate`, `avg_session_duration`, `goal_1_completions`, `goal_2_completions` enum* | metric field     |
| `campaign.clicks` |                                                                                                                                                                                                         | Campaign clicks  |
| `target.ctr`      |                                                                                                                                                                                                         | Target CTR       |

