#### Pagination <a name='Pagination' />
Indicates the number of records available

| Field      | Type                           | Example | Description                                                  |
|:-----------|--------------------------------|---------|--------------------------------------------------------------|
| **offset** | <a href='#Integer'>Integer</a> | 0       | starting index of the result set                             |
| **limit**  | <a href='#Integer'>Integer</a> | 100     | maximum possible records in the result set / page size       |
| **count**  | <a href='#Integer'>Integer</a> | 100     | actual number of records in the result set                   |
| **total**  | <a href='#Integer'>Integer</a> | 984     | total number of available records for the requested resource |

