# Pagination

| Field     | Type          | Comments|
|:----------|---------------|--|
| `offset`: | 0 (Integer)   |  |
| `limit`:  | 100 (Integer) |  |
| `count`:  | 100 (Integer) |  |
| `total`:  | 984 (Integer) |  |

