# Pagination <a name='Pagination' />

| Field    | Type                           | Example | Description |
|:---------|--------------------------------|---------|-------------|
| `offset` | <a href='#Integer'>Integer</a> | 0       |             |
| `limit`  | <a href='#Integer'>Integer</a> | 100     |             |
| `count`  | <a href='#Integer'>Integer</a> | 100     |             |
| `total`  | <a href='#Integer'>Integer</a> | 984     |             |

