# ReportingMetrics
 <a name='ReportingMetrics
' />

| Field         | Type                           | Example    | Description                |
|:--------------|--------------------------------|------------|----------------------------|
| `impressions` | <a href='#Integer'>Integer</a> | 21         | impressions                |
| `clicks`      | <a href='#Integer'>Integer</a> | 4          | clicks                     |
| `conversions` | <a href='#Integer'>Integer</a> | 2          | conversions                |
| `cost`        | <a href='#Decimal'>Decimal</a> | 1.09       | cost                       |
| `ctr`         | <a href='#Decimal'>Decimal</a> | 0.1905     | click through rate         |
| `ecpc`        | <a href='#Decimal'>Decimal</a> | 0.2725     | estimated cost per click   |
| `cpa`         | <a href='#Decimal'>Decimal</a> | 0.545      | cost per action            |
| `icr`         | <a href='#Decimal'>Decimal</a> | 0.09523810 | impression:conversion rate |

