# ReportingMetrics


| Field          | Type                 | Comments                   |
|:---------------|----------------------|----------------------------|
| `impressions`: | 21 (Integer)         | impressions                |
| `clicks`:      | 4 (Integer)          | clicks                     |
| `conversions`: | 2 (Integer)          | conversions                |
| `cost`:        | 1.09 (Decimal)       | cost                       |
| `ctr`:         | 0.1905 (Decimal)     | click through rate         |
| `ecpc`:        | 0.2725 (Decimal)     | estimated cost per click   |
| `cpa`:         | 0.545 (Decimal)      | cost per action            |
| `icr`:         | 0.09523810 (Decimal) | impression:conversion rate |

