# Rule
idResponse (object)

| Field        | Type                         | Comments|
|:-------------|------------------------------|--|
| `id`         | (Integer, required)          |  |
| `name`       | (string, required)           |  |
| `type`       | (RuleType, required)         |  |
| `conditions` | (array[Condition], required) |  |
| `filters`    | (array[Filter], required)    |  |

