#### Rule <a name='Rule' />
IdResponse (object)




| Field          | Type                                                   | Example     | Description                                            |
|:---------------|--------------------------------------------------------|-------------|--------------------------------------------------------|
| **id**         | <a href='#ID'>ID</a> *required*                        | 986         | rule primary identifier                                |
| **name**       | string *required*                                      | my ads rule | name of the rule                                       |
| **type**       | <a href='#RuleType'>RuleType</a> *required*            | `pause_ads` | determines what actions are performed on which objects |
| **conditions** | array of <a href='#Condition'>Condition</a> *required* |             | criteria for matching                                  |
| **filters**    | array of <a href='#Filter'>Filter</a> *required*       |             | restrict search to source, account, or campaign level  |

