# Rule <a name='Rule' />
IdResponse (object)

| Field        | Type                                                      | Example | Description |
|:-------------|-----------------------------------------------------------|---------|-------------|
| `id`         | <a href='#Integer'>Integer</a> required                   |         |             |
| `name`       | string required                                           |         |             |
| `type`       | <a href='#RuleType'>RuleType</a> required                 |         |             |
| `conditions` | <a href='#array[Condition]'>array[Condition]</a> required |         |             |
| `filters`    | <a href='#array[Filter]'>array[Filter]</a> required       |         |             |

