# RuleType <a name='RuleType' />
String describing the type of rule, indicating what it affects and how

| Value                   | Description                |
|:------------------------|----------------------------|
| `pause_campaign`        | Pause Campaigns            |
| `pause_ad`              | Pause Ads                  |
| `block_publisher`       | Block Publishers           |
| `block_section`         | Block Sections (Outbrain)  |
| `block_target`          | Block Targets (Revcontent) |
| `pause_ad_group`        | Pause Ad Groups (Yahoo)    |
| `modify_bid_publisher`  | Update Site Bid Modifiers  |
| `multiply_bid_target`   | Update Target Bids         |
| `multiply_bid_campaign` | Update Campaign Bids       |

