# SectionsReport <a name='SectionsReport' />

| Field                 | Type                                                         | Example                              | Description                          |
|:----------------------|--------------------------------------------------------------|--------------------------------------|--------------------------------------|
| `source_account_id`   | string                                                       |                                      | source's unique account identifier   |
| `source_campaign_id`  | string                                                       |                                      | source's unique campaign identifier  |
| `source_publisher_id` | string                                                       | "00a4cb19d55ea630d69fba33dba5d44106" | source's unique publisher identifier |
| `source_section_id`   | string                                                       | "00a4cb1d955ea603d69fb3a3dba54d1460" | source's unique section identifier   |
| `name`                | string                                                       | "Test Publisher"                     | name identifying section             |
| Include               | <a href='#ReportingMetrics'>ReportingMetrics</a>             |                                      |                                      |
| Include               | <a href='#GoogleAnalyticsMetrics'>GoogleAnalyticsMetrics</a> |                                      |                                      |

