# Source <a name='Source' />
String representing an ad network

| Value        | Description                                             |
|:-------------|---------------------------------------------------------|
| `outbrain`   | Outbrain ([www.outbrain.com](//www.outbrain.com))       |
| `taboola`    | Taboola ([www.taboola.com](//www.taboola.com))          |
| `revcontent` | Revcontent ([www.revcontent.com](//www.revcontent.com)) |
| `yahoo`      | Yahoo Gemini ([gemini.yahoo.com](//gemini.yahoo.com))   |
| `content-ad` | Content.ad ([www.content.ad](//content.ad))             |

