#### TargetsReport <a name='TargetsReport' />

| Field                  | Type                                                         | Example       | Description                         |
|:-----------------------|--------------------------------------------------------------|---------------|-------------------------------------|
| **source_account_id**  | <a href='#SourceID'>SourceID</a>                             |               | source's unique account identifier  |
| **source_campaign_id** | <a href='#SourceID'>SourceID</a>                             |               | source's unique campaign identifier |
| **source_target_id**   | <a href='#SourceID'>SourceID</a>                             |               | source's unique target identifier   |
| **name**               | string                                                       | "Test Target" | name identifying section            |
| Include                | <a href='#ReportingMetrics'>ReportingMetrics</a>             |               |                                     |
| Include                | <a href='#GoogleAnalyticsMetrics'>GoogleAnalyticsMetrics</a> |               |                                     |

