# User <a name='User' />
Describes a Brax user

| Field         | Type                             | Example | Description                               |
|:--------------|----------------------------------|---------|-------------------------------------------|
| username      | string                           |         | username                                  |
| email         | string                           |         | user's email                              |
| confirmed     | boolean                          |         | user's confirmed status                   |
| administrator | boolean                          |         | whether or not a user is an administrator |
| `created_at`  | <a href='#DateTime'>DateTime</a> |         | date and time the user was created        |
| `updated_at`  | <a href='#DateTime'>DateTime</a> |         | date and time the user was last updated   |

