#### User <a name='User' />
Describes a Brax user




| Field             | Type                             | Example                   | Description                               |
|:------------------|----------------------------------|---------------------------|-------------------------------------------|
| **username**      | string                           | ivan                      | username                                  |
| **email**         | string                           | user@site.com             | user's email                              |
| **confirmed**     | boolean                          | true                      | user's confirmed status                   |
| **administrator** | boolean                          | false                     | whether or not a user is an administrator |
| **created_at**    | <a href='#DateTime'>DateTime</a> | 2017-01-01T00:12:34+00:00 | date and time the user was created        |
| **updated_at**    | <a href='#DateTime'>DateTime</a> | 2017-02-03T13:45:01+00:00 | date and time the user was last updated   |

